mongodb/docs-compass

- source/install.txt
Adding additional details for Compass Windows installation.
CR: https://mongodbcr.appspot.com/140900001/
Staging link: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-892/install.html#install-on-windows
> DOCSP-892 - Adding details for Windows installation

- source/documents.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/35)
> Adding ref tag

- source/collections.txt
- source/databases.txt
- source/documents.txt
- source/includes/extracts-readonly-not-permitted-base.yaml
- source/includes/extracts-readonly-not-permitted.yaml
- source/includes/fact-readonly-nonpermitted-actions.rst
- source/index.txt
- source/indexes.txt
- source/release-notes.txt
- source/validation.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/42)
> Porting release notes and Compass Readonly from Beta

- source/install.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/46)
> DOCS-11612 - Updating Linux install paths and general cleanup

- source/release-notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/47)
> Updating release notes for 1.13

- source/faq.txt
- source/includes/fact-isolated-edition-firewall.rst
- source/install.txt
Code review: https://mongodbcr.appspot.com/210400002/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-2575/faq.html#why-are-some-features-of-compass-not-working
> DOCSP-2575 - Adding note about firewall reqs

- conf.py
- source/connect.txt
- source/faq.txt
- source/includes/steps-starting-compass.yaml
CR: https://mongodbcr.appspot.com/215470001/
> DOCSP-2974 - Adding faq note for how compass handles sensitive data

- conf.py
- source/install.txt
Review: https://mongodbcr.appspot.com/221570001/
> DOCS-11053 Tabbing out install page and updating download commands

- conf.py
- source/includes/fact-plugins-prereqs.rst
- source/install.txt
https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/master/install.html
> Fixing download URLs to use source constants

- source/import-export.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-3523/import-export.html
> (DOCSP-3523): Clarification note for export regarding project fields

- source/collections.txt
- source/import-export.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-3648/import-export.html
https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-3648/collections.html#view-collection-details
> (DOCSP-3648): Clarifying how to access import/export functionality

- conf.py
- source/index.txt
Updates the [index page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/anthonysansone/DOCSP-4438/index.html#compass-editions)
> (DOCSP-4438): Updated Compass main page.

- source/collections.txt
- source/databases.txt
- source/faq.txt
- source/includes/extracts-readonly-not-permitted-base.yaml
- source/includes/fact-isolated-edition-firewall.rst
- source/includes/fact-isolated-ver-third-party-mapping.rst
- source/index.txt
- source/release-notes.txt
- source/validation.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-4572/index.html
> (DOCSP-4572): Final updates to landing page

- source/index.txt
Staged: [Landing page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-5511/index.html)
> Tweaking license note on landing page

- conf.py
- source/troubleshooting/connection-errors.txt
Jira: https://jira.mongodb.org/browse/DOCSP-5803
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/tahiyachowdhury/DOCSP-5803/troubleshooting/connection-errors.html#solutions
> DOCSP-5803: Link to the server install guide on troubleshooting

- source/import-export.txt
- source/includes/steps-export.yaml
- source/includes/steps-import.yaml
Jira: https://jira.mongodb.org/browse/DOCSP-5705?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/tahiyachowdhury/DOCSP-5705/import-export.html#procedure
> (DOCSP-5705): Refactor Import / Export page to use step files (in progress)

- source/query-bar.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-4709
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/melissamahoney/DOCSP-4709/query-bar.html
> (DOCSP-4709): Remove bullet about $slice not being supported by project

- source/aggregation-pipeline-builder.txt
- source/views.txt
JIRA: [DOCSP-6510](https://jira.mongodb.org/browse/DOCSP-6510)
Staged: [Modfiy the source of a view](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-6510/views.html#modify-the-source-of-a-view)
> (DOCSP-6510): Modify a view

- source/collections.txt
- source/databases.txt
- source/documents/insert.txt
- source/import-export.txt
- source/includes/extracts-readonly-not-permitted-base.yaml
- source/indexes.txt
- source/performance.txt
- source/query-plan.txt
- source/validation.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-5746
Stage Links:
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/collections.html
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/validation.html
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/indexes.html
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/query-plan.html
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/documents/insert.html#limitation
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/import-export.html
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/databases.html …
> DOCSP-5746 update for Data Lake limitations

- source/collections.txt
- source/databases.txt
- source/documents/insert.txt
- source/import-export.txt
- source/includes/extracts-readonly-not-permitted-base.yaml
- source/indexes.txt
- source/performance.txt
- source/query-plan.txt
- source/validation.txt
This reverts commit b540cd757ef33a78f9ff20f32d679554189c52e7.
> Revert "DOCSP-5746 removing updates for Data Lake limitations (#170)"

- source/collections.txt
- source/databases.txt
- source/documents/insert.txt
- source/import-export.txt
- source/includes/extracts-readonly-not-permitted-base.yaml
- source/indexes.txt
- source/performance.txt
- source/query-plan.txt
- source/validation.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-5746
Stage links:
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/performance.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/databases.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/import-export.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/documents/insert.html#limitation
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/query-plan.html#visual-tree
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/indexes.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanase …
> DOCSP-5746 doc update for data lake related limitations

- source/release-notes.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-7993)
> (DOCSP-7993) Add missing date to release notes

- source/query/filter.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-8551)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-8551/query/filter.html#examples)
- Added the Examples section to the Query Your Data page
- Added sample data (two documents) and procedure for inserting through Compass
- Linked to Atlas sample data
- Added 4 examples: match, condition, date and array queries
- Linked to manual for more info/ examples
> (DOCSP-8551) Add example queries to Query Your Data page

- source/query/filter.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-8699)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-8699/query/filter.html#examples)
- Added a $not example
- Added a third document to sample data (without a name field) to better illustrate some results
- Updated all example results to be properly formatted JSON
> (DOCSP-8699) Add $not example to Query Your Data page

- source/connect.txt
- source/includes/steps-starting-compass-individual-fields.yaml
- source/release-notes.txt
Jira: https://jira.mongodb.org/browse/DOCS-13461
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/tahiya.chowdhury/DOCSP-13461/connect.html#considerations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/tahiya.chowdhury/DOCSP-13461/release-notes.html#compass-1-16
> (DOCSP-13461): Compass does not require a password for Kerberos authenticated connection but doc says required

- conf.py
- snooty.toml
- source/includes/steps-starting-compass-individual-fields.yaml
- source/upgrade.txt
https://jira.mongodb.org/browse/DOCSP-9267
> DOCSP-9267 - Change jmp parameter to tck.

- source/learn-more.txt
Jira: https://jira.mongodb.org/browse/DOCSP-9101
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/tahiya.chowdhury/DOCSP-9101/learn-more.html#mongodb-community-forums
> (DOCSP-9101): Update 'MongoDB Community Groups' resources in Compass docs

- source/connect.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-9298)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-9298/connect.html#connect-to-mongodb)
> (DOCSP-9298): Highlighting compass connection string options

- source/includes/steps-starting-compass-individual-fields.yaml
* Add notes to X509 subtab of connect procedure
* Remove SRV note
> (DOCS-13529) Clarify Compass X509 connections (#238)

- source/connect.txt
- source/includes/atlas-sample-data-note.rst
- source/index.txt
- source/manage-data.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-8705)
[Staged - landing](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-8705/index.html)
[Staged - connect](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-8705/connect.html)
> (DOCSP-8705) Add Atlas CTA to Compass

- source/connect.txt
- source/includes/atlas-sample-data-note.rst
- source/index.txt
- source/manage-data.txt
> (DOCSP-8705) Add Atlas CTA to Compass - backport (#246)

- source/connect.txt
[stage](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/typo-fix/connect.html#considerations)
> (typo-fix): authentication

- source/connect/favorite-connections.txt
- source/query/recent.txt
[JIRA - DOCSP-11744](https://jira.mongodb.org/browse/DOCSP-11744)
[Staged - Favorite Connection Considerations](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-11744/connect/favorite-connections.html#considerations)
> (DOCSP-11744): Add note for GNOME keyring

- conf.py
- source/import-export.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13118)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/test-beta/import-export.html#import-and-export-data-from-the-command-line)
> (DOCSP-13118) Fix dbtool links

- conf.py
[Subtask](https://jira.mongodb.org/browse/DOCSP-13146)
> (DOCSP-13146) update dbtools extlink

- source/index.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-13218/
> (DOCSP-13218): Clarify isolated edition

- source/includes/steps-starting-compass-individual-fields.yaml
[JIRA](https://jira.mongodb.org/browse/DOCSP-14022)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-14022/connect)
(click **Fill in Individual Fields** tab. In **Authentication** row in step 2, click **Kerberos** tab).
[build clean](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=600f2fad687cdd451a6dc291)
> (DOCSP-14022): remove password admonition for kerberos

- source/install.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60413cfe75e817aef7af67cb) has no issues
[Jira](https://jira.mongodb.org/browse/DOCSP-14404)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-14404/install/) -- choose the Windows tab.
> (DOCSP-14404) Add administrator reqs to installing on Windows

- source/aggregation-pipeline-builder.txt
- source/includes/steps-create-agg-pipeline.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-15305)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=608a18cd09293ae626b0d4a5) has no issues.
Made these changes:
- Edits, to clean up the existing content for [Aggregation Pipeline Builder](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-15305/aggregation-pipeline-builder/) and make it adhere to style guide by using the [Vale linter](https://github.com/10gen/mongodb-vale/blob/main/README.md).
- Added a line about changing width of the stage, in [Step 2](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-15305/aggregation-pipeline-builder/#fill-in-the-pipeline-stage) of this procedure.
Staging 1:  [Aggregation Pipeline …
> Edited aggregation pipeline doc, added that you can adjust stage width

- source/aggregation-pipeline-builder.txt
- source/includes/steps-create-agg-pipeline.yaml
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=608ad20109293ae626d44c45)
Backporting this change #345 
* Edited aggregation pipeline doc, added that you can adjust stage width
* copy review
> Edited aggregation pipeline doc, added that you can adjust stage width (#345)

- source/aggregation-pipeline-builder.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=608b3ac909293ae626eebb58)
Backporting #347
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/formatting-fix-beta/aggregation-pipeline-builder/#std-label-create-a-view)
> Formatting fix (backporting to beta) #347

- source/indexes.txt
JIRA: [DOCSP-16483](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-16483/indexes/#wildcard-indexes)
STAGING: [Wildcard Indexes](https://docs.mongodb.com/manual/core/index-wildcard/)
> (DOCSP-16483): Clarification for wildcard indexes

- source/collections.txt
@mongomoe, I added the same note from Atlas to Compass as well.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCS-14745/collections/#collection-information)
[JIRA](https://jira.mongodb.org/browse/DOCS-14745)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6124f15a7dcf0129305ae3c3)
> (DOCS-14745): Added note about the document count.

- source/faq.txt
We should clarify so it doesn't sound like Compass is expecting incoming connections to 3rd party services but rather Compass will attempt to connect to some external services.
JIRA:[ DOCSP-19387](https://jira.mongodb.org/browse/DOCSP-19387)
Staged: [FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-19387/faq/#why-are-some-features-of-compass-not-working-)
> (DOCSP-19387): Clarify language around external connections

- source/includes/steps-starting-compass-individual-fields.yaml
- source/release-notes.txt
Replica sets can connect using Socks5
JIRA: https://jira.mongodb.org/browse/DOCSP-20400?filter=-1
STAGING (Release notes): https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20400/release-notes/
(Connect Page): https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20400/connect/#connect-2
> DOCSP-20400 replica sets can connect using Socks5

- snooty.toml
- source/embedded-shell.txt
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20949-update-mongosh-naming/embedded-shell/
https://jira.mongodb.org/browse/DOCSP-20949
[COMPASS][MONGOSH] Update mongosh naming
> DOCSP- 20949 update mongosh naming

- source/connect/disconnect.txt
Compass Disconnect Procedure Page
JIRA: https://jira.mongodb.org/browse/DOCSP-20683
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20683/connect/disconnect/
> DOCSP-20683 Compass Disconnect Procedure Page

- source/connect/authentication-connection.txt
- source/connect/ssh-connection.txt
- source/connect/tls-ssl-connection.txt
Authentication page describing the contents of Authentication tab in new Compass Connection form.
JIRA: https://jira.mongodb.org/browse/DOCSP-20679 
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20679/connect/authentication-connection/
> DOCSP-20679 Authentication Page

- snooty.toml
- source/index.txt
- source/learn-more.txt
- source/release-notes.txt
* test fake manual url
* more fixes
* (DOCSP-20361): Subdomain consolidation content updates
* fix broken urls
* fix broken url
> (DOCSP-20361): Subdomain consolidation content updates (#388)

- .vscode/settings.json
- source/connect/tls-ssl-connection.txt
TLS/SSL page describing the contents of the TLS/SSL tab in the new Compass Connection form.
JIRA: https://jira.mongodb.org/browse/DOCSP-20680
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20680/connect/tls-ssl-connection/
> DOCSP-20680 TLS/SSL page

- source/connect/advanced-connection.txt
Page describing the contents of the Advanced connection tab in the new Compass connection form.
JIRA: https://jira.mongodb.org/browse/DOCSP-20682
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20682/connect/advanced-connection/
> DOCSP-20682 Advanced Connection Tab

- snooty.toml
- source/release-notes.txt
> (DOCSP-21732): 1.31.0 release notes

- source/connect/ssh-connection.txt
Proxy and SSH tunnel connection tab in the new Compass connection form. 
JIRA: https://jira.mongodb.org/browse/DOCSP-20681
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20681/connect/ssh-connection/
> DOCSP-20681 ssh and socks5

- snooty.toml
- source/release-notes.txt
Jira:
https://jira.mongodb.org/browse/DOCSP-21795
Build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624da2c90fdfea9c37eb9467
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-21795/release-notes/
> DOCSP-21795 1.31.1 compass release notes

- .vscode/settings.json
- snooty.toml
- source/collections.txt
- source/connect.txt
- source/connect/in-use-encryption.txt
Documenting the initial In-Use Encryption connection procedure. 
JIRA: https://jira.mongodb.org/browse/DOCSP-22743
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-22743/connect/in-use-encryption/#std-label-aws-compass-encryption
> DOCSP-22743 In-Use Encryption Procedure

- snooty.toml
- source/release-notes.txt
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-23756/release-notes/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62cefeb8230aeb802e27844d
> DOCSP-23756 Compass 1.3.3

- snooty.toml
- source/release-notes.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-24985
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-24985/release-notes/
> (DOCSP-24985): Compass 1.33.0 release notes

- source/install.txt
- source/release-notes.txt
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20940/release-notes/#compass-1.29.4)
- [Install Docs](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20940/install/)
https://jira.mongodb.org/browse/DOCSP-20940
> (DOCSP-20940): Mention m1 support

- source/connect/authentication-connection.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-25712
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-25712/connect/authentication-connection/#authenticate-as-a-different-kerberos-user-on-windows
> (DOCSP-25712): Re-add Kerberos auth behavior

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-26651)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=637d2774ed8015c14bd162eb)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26651-1.34.0-release-notes/release-notes/#compass-1.34.0)
> DOCSP-26651 1.34.0 release notes

- source/release-notes.txt
Backport of DOCSP-26651 to beta.
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=637e3d84ed8015c14b08dd3e)
> DOCSP-26651 1.34.1 release notes (backport to beta)

- source/connect.txt
- source/connect/connect-from-the-command-line.txt
- source/includes/intro-command-line-connection.rst
[STAGING - cmd line connect](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-25800-commandline-connection-support/connect/connect-from-the-command-line/)
[STAGING - connect](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-25800-commandline-connection-support/connect/#connecting-with-compass-from-the-command-line)
[JIRA](https://jira.mongodb.org/browse/DOCSP-25800)
> DOCSP-25800 command line connection support

- snooty.toml
- source/release-notes.txt
STAGE
-------
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27141/release-notes/#compass-1.34.2
BUILD
------
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63a1f80cdc742b91f203a476
JIRA
----
https://jira.mongodb.org/browse/DOCSP-27141
> DOCSP-27141 1.34.2 release notes

- source/command-line-options.txt
- source/connect/favorite-connections/import-export-cli/import.txt
- source/upgrade.txt
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27031/command-line-options/#options
https://jira.mongodb.org/browse/DOCSP-27031
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6397abe0dc742b91f2f593bf
> DOCSP-27031 Compass CLI options

- source/query/filter.txt
Fix typo on Query Your Data page. 
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-28833-query-data-typo/query/filter/#:~:text=not%20have%20a-,MongoDB,-deployment%20or%20if
https://jira.mongodb.org/browse/DOCSP-28833
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6421eedf66f244bf57e715c4
> DOCSP-28833 Query Your Data page Typo

- source/indexes.txt
Add index usage detail to the index page.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-28108/indexes/#indexes-tab
https://jira.mongodb.org/browse/DOCSP-28108
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64662700df0f8173e9b8b505
> DOCSP-28108 Add Index Usage Details

- snooty.toml
- source/release-notes.txt
1.37.0 Release notes and snooty.toml version bump.
https://docs-mongodborg-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30158/release-notes/
https://jira.mongodb.org/browse/DOCSP-30158
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64765a3767a273b8168847e1
> DOCSP-30158 1.37.0 Release Notes

- snooty.toml
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30285-download-compass/install/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-30285)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6479f8fa67a273b81661c9d5)
> DOCSP-30285 download compass

- source/aggregation-pipeline-builder.txt
Listing out stages available for use with the Stage Wizard.
QUESTION FOR REVIEWER: 
- Would it be better to put this information in the table with more in-depth descriptions of each use case as [outlined in the PD](https://docs.google.com/document/d/1yeGBHgb-nupd5PtA_9DuHX14yIoTngObKKZoTgLKPWM/edit#heading=h.ea8wetjwaqli) or would that create too much clutter considering those explanations are available in the UI text?
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29483-stage-wizard-use-cases/aggregation-pipeline-builder/#select-an-aggregation-pipeline-stage-use-case.
https://jira.mongodb.org/browse/DOCSP-29483
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=646ccf05df0f8173e9f5da99
[What's expected of an external …
> DOCSP-29483 Stage Wizard Aggregation Stages

- source/aggregation-pipeline-builder.txt
- source/in-use-encryption-tutorial.txt
Documents search input ability in the Stage Wizard (step 3)
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29657-stage-wizard-search-input/aggregation-pipeline-builder/#select-an-aggregation-pipeline-stage-use-case.
https://jira.mongodb.org/browse/DOCSP-29657
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6480eaeb67a273b816410633
> DOCSP-29657 Stage wizard search input

- source/connect/advanced-connection-options/authentication-connection.txt
- source/settings/settings-reference.txt
Added OIDC to settings and authentication connection.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29126/connect/advanced-connection-options/authentication-connection/#oidc
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29126/settings/settings-reference/#settings
https://jira.mongodb.org/browse/DOCSP-29126
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648b56d9259a8493e5a69901
> DOCSP-29126 Add OIDC to settings and authentication connection.

- snooty.toml
- source/release-notes.txt
1.38 Compass release notes.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30407-compass-release-notes/release-notes/#compass-1.38.0
https://jira.mongodb.org/browse/DOCSP-30407
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64937f65423952aeb92f3360
> DOCSP-30407-compass-release-notes

- source/install.txt
Updated all instances that state users should be running 3.6 or later to 4.2 or later
- Verified that we put 4.2 with Basit and Max Marcon via Slack 
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30811-min-support-version/install/#software-requirements (on all tabs)
https://jira.mongodb.org/browse/DOCSP-30811
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64933d28423952aeb917592a
> DOCSP-30811 Update Minimum Supported Version

- source/agg-pipeline-builder/create-a-view.txt
- source/agg-pipeline-builder/open-saved-pipeline.txt
- source/agg-pipeline-builder/save-agg-pipeline.txt
- source/create-agg-pipeline.txt
- source/includes/fact-save-pipeline.rst
- source/query/queries.txt
Moved content for [Save a Pipeline](https://www.mongodb.com/docs/compass/current/aggregation-pipeline-builder/#save-a-pipeline) into its own task page.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30593-save-pipeline-task/agg-pipeline-builder/save-agg-pipeline/
https://jira.mongodb.org/browse/DOCSP-30593
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648a0e2967a273b8163c5d95
> DOCSP-30593 Save a Pipeline Task Page

- source/agg-pipeline-builder/open-saved-pipeline.txt
- source/query/queries.txt
- Create task page for Open Saved Pipeline
- Content taken from the original [Aggregation Pipeline Builder section](https://www.mongodb.com/docs/compass/current/aggregation-pipeline-builder/#open-a-saved-pipeline)
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30594-open-saved-pipeline/agg-pipeline-builder/open-saved-pipeline/
https://jira.mongodb.org/browse/DOCSP-30594
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6495a29e423952aeb9bc88b7
> DOCSP-30594 Open Saved Pipeline

- source/troubleshooting/connection-errors.txt
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-8513/troubleshooting/connection-errors/#not-primary-or-secondary-is-not-writable
https://jira.mongodb.org/browse/DOCSP-8513
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649de396423952aeb9be41ab
> DOCSP-8513 Remove master terminology

- source/editions.txt
Requested changes: 
- "For View and optimize query performance with visual [explain plans",](https://docs.mongodb.com/compass/current/query-plan/#std-label-explain-plans) Compass Readonly is available (add a checkmark).
- Add a line for embedded shell support. Add checkmark for Stable and Isolated but not Readonly.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCS-14971-update-compass-editions-matrix/editions/#capabilities-of-compass-short-editions
https://jira.mongodb.org/browse/DOCS-14971
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64aece50423952aeb995f03b
> DOCS-14971 Update Compass Editions Matrix

- snooty.toml
- source/release-notes.txt
Add release notes for Compass 1.38.2 and 1.39.0
[Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-31109/release-notes/)
- https://jira.mongodb.org/browse/DOCSP-31109
- https://jira.mongodb.org/browse/DOCSP-31219
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b81ca987b3b360460b9659
> (DOCSP-31109,DOCSP-31219): Compass 1.38.2 and 1.39.0 release notes

- source/views.txt
Updated steps across the page to reflect accurate, updated UI.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30796-compass-ui-views/views/
https://jira.mongodb.org/browse/DOCSP-30796
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b6fa4b87b3b360469f7831
> DOCSP-30796 Update Views UI Information

- source/agg-pipeline-builder/pipeline-custom-collation.txt
- source/create-agg-pipeline.txt
Compass Agg Pipeline Builder Refactor: 
- Migrates content from existing section in [Aggregation Pipeline Builder page ](https://www.mongodb.com/docs/compass/current/aggregation-pipeline-builder/#specify-custom-collation) to separate task page.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30597-custom-collation-compass/agg-pipeline-builder/pipeline-custom-collation/
https://jira.mongodb.org/browse/DOCSP-30597
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b8509a87b3b36046287174
> DOCSP-30597 Specify Custom Collation

- source/connect/advanced-connection-options/authentication-connection.txt
- source/settings/settings-reference.txt
Compass OIDC docs merge into master
Authentication Connection: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/oidc-docs/connect/advanced-connection-options/authentication-connection/#oidc
Settings: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/oidc-docs/settings/settings-reference/#settings
https://jira.mongodb.org/browse/DOCSP-30147?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64932693259a8493e571dbdc
> Compass OIDC-docs merge into master

- source/agg-pipeline-builder/create-a-view.txt
- source/agg-pipeline-builder/maxtime-ms-pipeline.txt
- source/agg-pipeline-builder/open-saved-pipeline.txt
- source/agg-pipeline-builder/pipeline-custom-collation.txt
- source/agg-pipeline-builder/save-agg-pipeline.txt
- source/agg-pipeline-builder/view-pipeline-explain-plan.txt
- source/create-agg-pipeline.txt
Create an "Create a View from Pipeline Results" task page. Source material from [here](https://www.mongodb.com/docs/compass/current/aggregation-pipeline-builder/#create-a-view-from-pipeline-results).
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-31488-create-view-from-pipeline/agg-pipeline-builder/create-a-view/
https://jira.mongodb.org/browse/DOCSP-31488
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64dcffb367dbe910102fea23
> DOCSP-31488 Create a View from Pipeline Results

- source/agg-pipeline-builder/count-pipeline-results.txt
- source/create-agg-pipeline.txt
Create an "Count Pipeline Result Documents" task page. Source material from [here](https://www.mongodb.com/docs/compass/current/aggregation-pipeline-builder/#refresh-document-counts).
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-31489-refresh-document-counts/agg-pipeline-builder/count-pipeline-results/
https://jira.mongodb.org/browse/DOCSP-31489
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e3a60b57e37806c5fb355c
> DOCSP-31489 Count Result Documents

- source/agg-pipeline-builder/aggregation-pipeline-builder-settings.txt
- source/create-agg-pipeline.txt
Created a reference page for the Aggregation Pipeline Builder Settings. 
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-31490-pipeline-settings-reference/agg-pipeline-builder/aggregation-pipeline-builder-settings/
https://jira.mongodb.org/browse/DOCSP-31490
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e5325457e37806c55e048c
> DOCSP-31490 Pipeline Settings Reference Page

- source/release-notes.txt
Release notes for Compass 1.39.1.
[RN](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32063-compass-1.39.1-release-notes/release-notes/#compass-1.39.1)
* [DOCSP-32063](https://jira.mongodb.org/browse/DOCSP-32063)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d4393267dbe910106549a7)
> DOCSP-32063 compass 1.39.1 release notes

- snooty.toml
- source/release-notes.txt
Confirmed with dev that there are no user-facing changes that we want to announce for this release.
https://preview-mongodbjeffallenmongo.gatsbyjs.io/compass/DOCSP-32653/release-notes/
https://jira.mongodb.org/browse/DOCSP-32653
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ee590524fcc731b49cd45c
> (DOCSP-32653): Compass 1.39.3 release notes

- source/release-notes.txt
Compass 1.39.4 Release notes.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32887-1.39.4-release/release-notes/#compass-1.39.4
https://jira.mongodb.org/browse/DOCSP-32897
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64f86c0e24fcc731b4b9c4b1
> DOCSP-32887 Compass 1.39.4 Release

- source/facets.toml
https://jira.mongodb.org/browse/DOCSP-32483
Hi @sarah-olson-mongodb -
Here's the facet.toml file for the compass repo.  Please merge if it looks good to you!
Thank you!
Sarah
> DOCSP-32483 programmatic tagging script for compass repo

- snooty.toml
- source/release-notes.txt
I accidentally somehow pushed in a previous PR that was a merge conflict on my end. I fixed it and removed the merge conflict part.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6500be3724fcc731b482233a
> merge conflict fix

- snooty.toml
- source/includes/fact-atlas-compatible.rst
- source/includes/fact-atlas-link.rst
- source/includes/fact-environments.rst
- source/install.txt
- source/query/filter.txt
- source/query/sort.txt
Cherry picking #547  to the beta branch.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6500c84624fcc731b485375c
- [] Is this free of any warnings or errors in the RST?
> DOCSP-32260 adds atlas centric cta

- source/collections.txt
- source/connect.txt
- source/import-export.txt
- source/install.txt
- source/query/filter.txt
- source/query/queries.txt
- source/query/sort.txt
Hi @sarah-olson-mongodb & @mdb-ashley!  Here are the manual tags for the top 250 /docs-compass/ pages.  Please merge if everything looks good!
Thank you!
Sarah
https://jira.mongodb.org/browse/DOCSP-27817
> DOCSP-27817 manual tags for compass repo

- source/query-with-natural-language/prompt-natural-language-aggregation.txt
Prompt your first aggregation page.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32901/query-with-natural-language/prompt-natural-language-aggregation/
https://jira.mongodb.org/browse/DOCSP-32901
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650b0b3a492df295cf20aa48
> DOCSP-32901 Prompt your First GAI Aggregation

- snooty.toml
- source/query-with-natural-language/enable-natural-language-querying.txt
- source/settings/settings-reference.txt
Content for enabling the generative AI query feature for Compass.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32898/query-with-natural-language/enable-natural-language-querying/
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32898/settings/settings-reference/#settings
https://jira.mongodb.org/browse/DOCSP-32898
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650b11a3492df295cf23abbf
> DOCSP-32898 Enable Natural Language Querying

- source/index.txt
Adding GAI content to Compass landing page.
https://docs-mongodborg-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-33190/
https://jira.mongodb.org/browse/DOCSP-33190
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650b1718492df295cf26ca3f
> DOCSP-33190 Update Compass Landing Page with GAI

- source/collections.txt
- source/connect.txt
- source/import-export.txt
- source/install.txt
- source/query/filter.txt
- source/query/queries.txt
- source/query/sort.txt
@sarah-olson-mongodb, this PR should resolve facet spacing issues that were my mistake.
> DOCSP-27817 fix to facet spacing

- source/release-notes.txt
Release Notes for Compass 1.40.0
https://preview-mongodbjeffallenmongo.gatsbyjs.io/compass/DOCSP-33292/release-notes/#compass-1.40.0
https://jira.mongodb.org/browse/DOCSP-33292
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6512f676492df295cff1b5ac
> (DOCSP-33292): Compass 1.40.0 release notes

- snooty.toml
> update snooty.toml for 1.40.0

- snooty.toml
- source/release-notes.txt
Compass release notes for 1.4.2 and 1.4.1.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-33329/release-notes/#compass-1.40.2
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-33329/release-notes/#compass-1.40.1
https://jira.mongodb.org/browse/DOCSP-33329
https://jira.mongodb.org/browse/DOCSP-33321
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65157de0492df295cfa14fcb
> DOCSP-33329 1.4.1 1.4.2 Release Notes

- source/keyboard-shortcuts.txt
Correction to Prettify shortcut key in Compass and a few other corrections to Mac commands.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-33403/keyboard-shortcuts/
https://jira.mongodb.org/browse/DOCSP-33403
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65171632492df295cf115f27
> DOCSP-33403 Correct Prettify Code Shortcut

- snooty.toml
- source/query-with-natural-language/enable-natural-language-querying.txt
- source/release-notes.txt
1.40.3 Compass Release Notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-33342/release-notes/#compass-1.40.3
https://jira.mongodb.org/browse/DOCSP-33342
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65295977673b813c8f3ac1dc
> DOCSP-33342 1.40.3 Release Notes

- source/query-with-natural-language/enable-natural-language-querying.txt
- source/settings/config-file.txt
Adding config file entry for Compass Generative AI feature.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-33663/settings/config-file/
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-33663/query-with-natural-language/enable-natural-language-querying/#before-you-begin
https://jira.mongodb.org/browse/DOCSP-33663
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=652ea8b1673b813c8f5b3770
> DOCSP-33663 Generative AI Config File Setting

- .github/workflows/vale-tdbx.yml
> (DOCSP-34004): Enable Vale GitHub action

- source/install.txt
removing section on rosetta 
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-28405/install/#software-requirements-1
https://jira.mongodb.org/browse/DOCSP-28405
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6553ce7f5b686d6bd94cbea7
> DOCSP-28405 removing rosetta section

- source/learn-more.txt
Updating university courses
https://preview-mongodbjocelynmendez1.gatsbyjs.io/compass/DOCSP-33798/learn-more/#free-mongodb-courses-online
https://jira.mongodb.org/browse/DOCSP-33798
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65578d1d5b686d6bd9557c21
> DOCSP-33798 Update university courses

- source/install.txt
- source/release-notes.txt
Since 13.8.0, Compass now requires Windows 10 or later.
- https://preview-mongodbmongocaleb.gatsbyjs.io/compass/DOCSP-34681/install/
- https://preview-mongodbmongocaleb.gatsbyjs.io/compass/DOCSP-34681/release-notes/#compass-1.38.0
https://jira.mongodb.org/browse/DOCSP-34681
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6570b6327a5cb5fef57c12a7
> Update Windows version requirements

- source/release-notes.txt
Release notes for Compass v1.40.5
[RN](https://preview-mongodbkennethdyer.gatsbyjs.io/compass/DOCSP-34812-compass-1.40.5/release-notes/#compass-1.40.5)
[DOCSP-34812](https://jira.mongodb.org/browse/DOCSP-34812)
* [2023-12-11](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65776d967a5cb5fef51451cd)
* [2024-01-18](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a9a2a08aeba96efb394d15)
* [2024-01-19](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65aad3b40949a5aff77295e1)
> DOCSP-34812 v1.40.5 Release Notes

- source/query/filter.txt
Include example that demonstrates how to query by substring.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-32833/query/filter/#match-by-substring
https://jira.mongodb.org/browse/DOCSP-32833
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c11f1d6b2f17c95a0179bf
> DOCSP-32833 address feedback on Query Your Data

- source/indexes.txt
- source/indexes/create-vector-search-index.txt
Adds how to create an Atlas Vector Search Index
https://preview-mongodbjocelynmendez1.gatsbyjs.io/compass/DOCSP-34578/indexes/create-vector-search-index/
https://jira.mongodb.org/browse/DOCSP-34578
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cda1177111165982c36ae8
> DOCSP-34578 Vector search index

- source/release-notes.txt
Adding 1.4.1 Compass Release Notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-36564/release-notes/#compass-1.42.1
https://jira.mongodb.org/browse/DOCSP-36564
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ce6e947111165982046bde
> DOCSP-36564 1.4.1 Release Notes

- source/indexes/create-search-index.txt
- source/query/atlas-search.txt
- source/query/filter.txt
Document option to direct run an aggregation using a Search Index. Also added documentation to edit search and vector search indexes and run vector search queries.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-33295/query/atlas-search/
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-33295/indexes/create-search-index/
https://jira.mongodb.org/browse/DOCSP-33295
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ce62a67111165982ffa6fe
> DOCSP-33295 Allow user to Run Aggregate

- source/includes/steps-create-index.yaml
Updates collation options dropdowns with a text box in the documentation.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-24114/indexes/#optional-specify-index-options
https://jira.mongodb.org/browse/DOCSP-24114
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ce667b71111659820139cd
> DOCSP-24114 Replace collation options dropdowns with an editor

- source/query/maxtimems.txt
Mentions OnlineArchive on compass MaxTimeMS page.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-35840/query/maxtimems/
https://jira.mongodb.org/browse/DOCSP-35840
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ccf00ecbcd269fa52d56d7 (clean)
> DOCSP-35840 Mention OnlineArchive on compass MaxTimeMS docs

- source/query/filter.txt
- source/schema.txt
- Move Compass Sampling note from filter page to schema page
https://preview-mongodbajhuhmdb.gatsbyjs.io/compass/DOCSP-37457-compass-sampling-note/schema/#query-bar
Removed content from: https://preview-mongodbajhuhmdb.gatsbyjs.io/compass/DOCSP-37457-compass-sampling-note/query/filter/
https://jira.mongodb.org/browse/DOCSP-37457
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65eb39326fc5f04850a22695
> DOCSP-37457 Move Compass Sampling Note

- source/release-notes.txt
Compass 1.42.2 Release Notes
https://preview-mongodbjmdmongo.gatsbyjs.io/compass/DOCSP-37164/release-notes/#compass-1.42.2
https://jira.mongodb.org/browse/DOCSP-37164
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f1ebe86fc5f048502b68b7
> DOCSP-37164 Compass 1.42.2 Release Notes

- source/connect.txt
- source/includes/multiple-connections.rst
- source/includes/starting-compass-paste-string.rst
Adding note about multiple connections and clarifying connection steps
note for reviewers: Release version for multiple connections is tbd so the version number will change before release 
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-37462/connect/
https://jira.mongodb.org/browse/DOCSP-37462
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661431ff3a5920a29144f724
> DOCSP 37462 Updating Connect to MonogDB Compass page for multiple connections

- source/query/filter.txt
adds an example of querying on a nested field
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-38471/query/filter/#match-by-nested-field
https://jira.mongodb.org/browse/DOCSP-38471
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6616d9be3a5920a291ed9009
> DOCSP-38471 adding query on nested fields example

- source/import-export.txt
removing extra keywords on import-export page
N/A
https://jira.mongodb.org/browse/DOCSP-38536
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66227619132d178bc1c80987
> DOCSP-38536 removing extra keywords on import-export page

- source/includes/fact-protect-connection-strings.rst
- source/settings/command-line-options.txt
Add compass command line options
https://preview-mongodbjocelynmendez1.gatsbyjs.io/compass/DOCSP-38420/settings/command-line-options/
https://jira.mongodb.org/browse/DOCSP-38420
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662fb4fab67dbf804a45200f
> DOCSP-38420 Add compass command line options

- source/install.txt
Updating minimum Ubuntu version to 16.04
(release note update will happen in the release note ticket)
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-38793/install/#software-requirements-2
https://jira.mongodb.org/browse/DOCSP-38793
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663290b6b67dbf804a0a0997
> DOCSP-38793 updating minimum ubuntu and RHEL version

- source/release-notes.txt
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-40373/release-notes/#compass-1.43.1
https://jira.mongodb.org/browse/DOCSP-40373
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666af606ebce19f3148906c8
> DOCSP-40373 1.43.1 Release Notes

- source/install.txt
Updates minimum version of Ubuntu to 20.04 and minimum version of MongoDB to 4.4 for each OS.
https://preview-mongodbjmdmongo.gatsbyjs.io/compass/DOCSP-40733/install/#software-requirements-2
https://jira.mongodb.org/browse/DOCSP-40733
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66759587ebce19f314ddf36a
> DOCSP-40733 updates applicable versions

- source/indexes.txt
added a bullet for limitations to Compass documentation and a Tip
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/compass/DOCSP-40216/indexes/#limitations
https://jira.mongodb.org/browse/DOCSP-40216
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6679cb54ebce19f314b186fe
> DOCSP-40216 Add search index management limitations compass

- snooty.toml
- source/includes/verification-gpg-results.rst
- source/includes/verify-signatures-before-you-begin.rst
- source/includes/verify-signatures-intro.rst
- source/install.txt
- source/install/verify-signatures.txt
- source/install/verify-signatures/disk-images.txt
- source/install/verify-signatures/gpg.txt
- source/install/verify-signatures/rpm.txt
- source/install/verify-signatures/windows.txt
Add docs to verify Compass package signatures.
[Verify Integrity of Compass Packages](https://preview-mongodbjeffallenmongo.gatsbyjs.io/compass/DOCSP-38230/install/verify-signatures/) (and subpages)
https://jira.mongodb.org/browse/DOCSP-38230
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667b0aeaebce19f31403513b
> (DOCSP-38230): Verify Compass signatures

- source/release-notes.txt
Release notes per JIRA.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/compass/DOCSP-40957-1.43.3-release-notes/release-notes/#compass-1.43.3
https://jira.mongodb.org/browse/DOCSP-40957
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667ee4edfe162e50060c8888
> DOCSP-40957-1.43.3-release-notes

- source/keyboard-shortcuts.txt
Keyboard shortcut per JIRA.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/compass/DOCSP-39552-keyboard-update/keyboard-shortcuts/#keyboard-shortcuts
https://jira.mongodb.org/browse/DOCSP-39552
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667c4853ebce19f314525f7f
> DOCSP-39552-keyboard-update

- source/install.txt
Update Linux .dep installation instructions to modern approaches
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-40655/install/#download-and-install-compass-1
https://jira.mongodb.org/browse/DOCSP-40655
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667c776febce19f314617eac
> DOCSP-40655 Update Linux .dep installation instructions

- snooty.toml
- source/release-notes.txt
Compass 1.43.4 release notes
https://preview-mongodbajhuhmdb.gatsbyjs.io/compass/DOCSP-41050-compass-1.43.3/release-notes/
https://jira.mongodb.org/browse/DOCSP-41050
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66830561fe162e5006d980bc
> DOCSP-41050-Compass-1.43.4

- snooty.toml
- source/release-notes.txt
- `1.43.5` Compass release notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-42028/release-notes/#compass-1.43.5
https://jira.mongodb.org/browse/DOCSP-42028
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66abea46824f175afdd4ff57
> DOCSP-42028-1435-releasenotes

- source/release-notes.txt
Release notes for 1.43.6
[RN](https://preview-mongodbkennethdyer.gatsbyjs.io/compass/DOCSP-42839-1.43.6-RN/release-notes/#compass-1.43.6)
[DOCSP-42839](https://jira.mongodb.org/browse/DOCSP-42839)
* [2024-08-23](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c901a025dc1b90c769073a)
> DOCSP-42839 RN 1.43.6

- source/release-notes.txt
Fixed 404 link to 5.1 release notes
[Compass 1.29.4](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/compass/DOCSP-41688-relnotes-link/release-notes/#compass-1.29.4)
https://jira.mongodb.org/browse/DOCSP-41688
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66d729d304d83d6693a01e2d
> DOCSP-41688 Fixed relnotes link

- source/release-notes.txt
Compass 1.44.0 Release Notes
https://deploy-preview-667--docs-compass.netlify.app/release-notes/
https://jira.mongodb.org/browse/DOCSP-43235
See Netlify comment
> DOCSP-43235: Initial 1.44.0 Release Note updates

- source/release-notes.txt
- Compass 1.44.3 release notes
- Documents QE range (discussed w/ Betsy & Gaurab that this will only be mentioned in the release notes) 
https://deploy-preview-670--docs-compass.netlify.app/release-notes/#compass-1.44.3
https://jira.mongodb.org/browse/DOCSP-43272
> DOCSP-43272 Compass 1.44.3

- source/release-notes.txt
- Compass 1.44.4 release notes ([GH release notes](https://github.com/mongodb-js/compass/releases/tag/v1.44.4))
https://deploy-preview-669--docs-compass.netlify.app/release-notes/#compass-1.44.4
https://jira.mongodb.org/browse/DOCSP-43659
> DOCSP-43659 Compass 1.44.4

- source/keyboard-shortcuts.txt
Removed Web Shell -> Toggle shell as the shell is now a tab. 
https://deploy-preview-675--docs-compass.netlify.app/keyboard-shortcuts/
https://jira.mongodb.org/browse/DOCSP-43357
> DOCSP-43357-remove-toggle-shell

- source/collections.txt
- source/databases.txt
- source/documents.txt
- source/views.txt
Updates headings for SEO 
https://deploy-preview-690--docs-compass.netlify.app/databases/
https://deploy-preview-690--docs-compass.netlify.app/collections/
https://deploy-preview-690--docs-compass.netlify.app/views/
https://deploy-preview-690--docs-compass.netlify.app/documents/
https://jira.mongodb.org/browse/DOCSP-44866
> DOCSP-44866-improving-headings

- source/release-notes.txt
- Compass 1.45.0 release notes
https://deploy-preview-706--docs-compass.netlify.app/release-notes/#compass-1.45.0
https://jira.mongodb.org/browse/DOCSP-46067
> DOCSP-46067 Compass 1.45.0 RN

- source/release-notes.txt
Changed year from 2024 to 2025
https://jira.mongodb.org/browse/DOCSP-46851
> DOCSP-46851-compass-release-year

- source/connect/connections.txt
Reword [connection instructions](https://www.mongodb.com/docs/compass/current/connect/connections/) according to [figma designs. ](https://www.figma.com/email_only)
https://deploy-preview-717--docs-compass.netlify.app/connect/connections/#connect-to-mongodb
https://jira.mongodb.org/browse/DOCSP-45342
> DOCSP-45342-add-connect-button

- source/agg-pipeline-builder/count-pipeline-results.txt
- source/agg-pipeline-builder/create-a-view.txt
- source/agg-pipeline-builder/export-pipeline-results.txt
- source/agg-pipeline-builder/export-pipeline-to-language.txt
- source/agg-pipeline-builder/maxtime-ms-pipeline.txt
- source/agg-pipeline-builder/pipeline-custom-collation.txt
- source/agg-pipeline-builder/view-pipeline-explain-plan.txt
- source/collections.txt
- source/collections/capped-collection.txt
- source/collections/clustered-collection.txt
- source/collections/collation-collection.txt
- source/collections/encrypted-collection.txt
- source/collections/time-series-collection.txt
- source/create-agg-pipeline.txt
- source/databases.txt
- source/documents.txt
- source/export-query-to-language.txt
- source/indexes.txt
- source/query-plan.txt
Address feedback from Julia on the Cloud team for further Compass cleanup prior to merging this content into the Data Explorer docs:
- Check across the docs for consistency regarding adding :guilabel: to procedure steps
- One of the images in pipeline-custom-collation.txt has an extra slash
- Investigate whether we can use shared nav steps
- In capped-collection.txt, adjust wording online 49 to "that you can use" as opposed to "that can be used"
- In capped-collection.txt, adjust wording on line 55 to "you can't adjust"
- Rename all "Restrictions" or "Restrictions and Limitations" headings to just "Limitations" and move them all to above the procedures
Renamed "Restrictions" to "Limitiations" for concistency with all other docs pages + moved limitations to before the procedures: 
- …
> DOCSP-47239 More Compass Cleanup

- source/connect.txt
Provides some more examples of advanced connection strings in common pain point areas for users on Compass [connect page](https://www.mongodb.com/docs/compass/current/connect/).
https://deploy-preview-726--docs-compass.netlify.app/connect/
https://jira.mongodb.org/browse/DOCSP-45614
> DOCSP-45614-connection-string-examples

- snooty.toml
Changed "title", not "siteName" (which doesn't exist).
https://deploy-preview-734--docs-compass.netlify.app/
See the name to right of ToC on left pane.
https://jira.mongodb.org/browse/DOCSP-48292
> DOCSP-48292-site-name-change

- source/connect/advanced-connection-options/authentication-connection.txt
Clarify use of OIDC endpoint requirement 
https://deploy-preview-740--docs-compass.netlify.app/connect/advanced-connection-options/authentication-connection/
https://jira.mongodb.org/browse/DOCSP-48743
https://app.netlify.com/sites/docs-compass/deploys/67f4389485c1ad0008c126cb
> DOCSP-48743-clarify-endpoint-req

- source/upgrade.txt
Add note about continuous delivery for compass
https://deploy-preview-745--docs-compass.netlify.app/upgrade/
https://jira.mongodb.org/browse/DOCSP-49275
https://app.netlify.com/sites/docs-compass/deploys/67f97c0f39612e00088e5089
> DOCSP-49275-continuous-delivery
