source/includes/steps-starting-compass.yaml
Hostname tip for Compass connect was inaccurate - Fixing it up with accurate info.  After code review, version info was added.
CodeReview: https://mongodbcr.appspot.com/149550001/
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCS-10634/connect.html
=> DOCS-10634 - Fixing hostname tip for Compass connect

source/collections.txt, source/databases.txt, source/documents.txt, source/includes/extracts-readonly-not-permitted-base.yaml, source/includes/extracts-readonly-not-permitted.yaml, source/includes/fact-readonly-nonpermitted-actions.rst, source/index.txt, source/indexes.txt, source/release-notes.txt, source/validation.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-1503/index.html
Copy review: https://mongodbcr.appspot.com/174990001/
I've updated the index page with a description of the new Readonly version. I've also including a warning on the relevant pages indicating which actions cannot be performed in the readonly edition.
Release notes have also been updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/38)
=> DOCSP-1503 - Documenting Compass Readonly mode

source/release-notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/43)
=> Typo in release notes

source/aggregation-pipeline-builder.txt, source/faq.txt, source/includes/fact-isolated-ver-third-party-mapping.rst, source/index.txt, source/release-notes.txt, source/schema.txt
Staged view: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-2285/index.html#compass-isolated
These changes should cover everything we need to address for Compass Isolated Edition. All relevant pages have had a note added where their functionality does not work with isolated version.
Also some minor tweaks to the structure of the index page since it no longer made sense to lump the Readonly / Isolated versions of Compass in with GA and Beta, since there are GA and Beta versions of both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-compass/49)
=> DOCSP-2285 - Document Compass Isolated Version

source/aggregation-pipeline-builder.txt
Adds notes on the sample mode and comment mode now in the builder.
=> Add documentation on agg pipeline builder modes.

source/import-export.txt
A note if you happen to test this procedure - there's a known bug where importing with CSV results in an extra, blank document.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-3253/import-export.html
=> DOCSP-3253 - Adding CSV example for import

source/includes/steps-create-validation-rule-via-builder.yaml, source/includes/steps-create-validation-rule-via-json.yaml, source/validation.txt
This is largely refactoring / reorganization. I also moved this page to under the Documents page in the ToC, since I think it makes more sense there.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-2594/validation.html
=> (DOCSP-2594): Updates and refactors to Document Validation page

source/query-bar.txt, source/query-plan.txt, source/schema.txt
My original draft had an contextual sentence so this would read:
```
MongoDB Compass does not support the $near and $nearSphere geospatial query operators in any of the query bar fields. These operators do not provide any additional functionality in the :ref:`schema view <schema-tab>`.
```
But that didn't seem necessary. Just curious if you think it might help provide some context as to *why* we do not support these operators (at this time).
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-3810/query-bar.html
=> (DOCSP-3810): Compass does not support near / nearshpere

source/includes/fact-connect-auth-info.rst, source/includes/list-table-ssh-connection.rst, source/includes/list-table-ssl-connection.rst, source/includes/list-table-unencrypted-connection.rst, source/includes/steps-starting-compass.yaml
Kerberos connections now provide a toggle in the UI to optionally canonicalize host names. As part of these changes, I have also done some refactoring to use tabs for the auth mechanisms, since prior we were not providing any descriptions of the mechanisms and their required fields.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-3809/connect.html
=> (DOCSP-3809): Added support for canonicalize host name via Kerberos

source/index.txt, source/indexes.txt, source/submit-feedback.txt
Cleaned up the copy on the landing page and separated the Contact section to a new page.
I also added an image to the landing page, so users have an idea of what Compass actually looks like. Do we like this? Yay or neigh 🐴 ? I wasn't sure if it looked best before or after the Overview section.
Staged view: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-4315/index.html
New Feedback page: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-4315/submit-feedback.html
=> (DOCSP-4315): Landing page cleanup

source/query-bar.txt
Made the following changes:
- Changed the TOC depth of the [Query Bar](https://docs-mongodbcom-staging.corp.mongodb.com/compass/melissamahoney/DOCSP-4618/query-bar.html) page to 2 so that the operators are easier to find
- Created a [Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/compass/melissamahoney/DOCSP-4618/query-bar.html#limitations) section
- Removed the note from the overview and added it as a bullet in the new Limitations section
- Added a bullet to note that the $slice operator doesn't work for projection
=> DOCSP-4618: Note that $slice operator doesn't work for projection

conf.py, source/includes/steps-create-index.yaml
Compass supports creating wildcard indexes. There is a bit of refactoring done as part of this change. Now, instead of linking the index options and linking out to more information, we include a brief one-line description of each option. We still link out to the manual for more info.
JIRA: [DOCSP-5918](https://jira.mongodb.org/browse/DOCSP-5918)
Staged: [Index Options](https://docs-mongodbcom-staging.corp.mongodb.com/compass/jeffreyallen/DOCSP-5918/indexes.html#optional-specify-the-index-options)
=> (DOCSP-5918): Support for wildcard indexes

source/release-notes.txt
[Staged view](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/1.20-release-notes/release-notes.html)
[Compass releases](https://github.com/mongodb-js/compass/releases)
[UUID queries in 1.20](https://jira.mongodb.org/browse/DOCSP-6645) (approved for release notes via Slack conversation)
[Note: final keychain requests when updating to 1.20](https://jira.mongodb.org/browse/DOCSP-6962)
*These release notes still need an exact date.
=> 1.20 release notes

source/documents/view.txt
Want to clarify that Compass only refreshes the documents view when you run a new query. Re-running the same query does not return new documents.
Staged: [Refresh Behavior](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-6064/documents/view.html#document-refresh-behavior)
=> (DOCSP-6064): Clarify Compass refresh behavior for documents

source/release-notes.txt
Adding a missing release note for a 1.20 feature (docs for that feature already merged to master and beta).
=> Add "export driver syntax" release note

source/indexes.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-8369)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-8369/indexes.html)
Added an untitled overview section that provides some context for a user who doesn't know what indexes are or how to use them. It's meant to frame the page or get them started reading the server docs.
Added an admonition calling out potential tradeoffs.
=> (DOCSP-8369) Explain what indexes are on the Manage Indexes page

source/index.txt, source/upgrade.txt
This is basically the content, I'll leave formatting decisions up to the docs team. :)
We just need a section in the docs to tell people how to migrate from Compass Community to Compass and a note that Compass Community is deprecated.
=> COMPASS-3986: Adding migration information to docs

source/upgrade.txt
Just tried this and it looks like `%APPDATA%`
already points to the `Roaming` directory.
=> Fixed preferences path on Windows

source/includes/steps-starting-compass-individual-fields.yaml
[Ticket](https://jira.mongodb.org/browse/DOCS-13529)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCS-13529/connect.html#connect)
Changes are under "Fill in Individual Fields" > "X.509":
- Added a note about Atlas-managed certs
- Added a note about using SRV records
This change will need to be ported to beta.
=> (DOCS-13529) Clarify Compass X509 connections

source/faq.txt, source/includes/extracts-query-bar.yaml, source/includes/toc-manage-data.yaml, source/manage-data.txt, source/sampling.txt, source/schema.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-4806)
[Staged view](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-4806/sampling.html)
- Moved sampling content from FAQ page to new Sampling page
- Sampling page is under "Interact with Your Data"
- Updated notes ([example staged note](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-4806/documents.html#manage-documents)) and links for new page
- Rewrote some of the sampling information
Questions for (probably tech) reviewer:
- ~~Is MongoDB 3.0 the earliest version that sampling is supported in Compass?~~
- Can ``sampleSize`` be changed from 1000? My understanding is that it can't be, so instead of mentioning it at all I just said "1000 documents" outright.
=> (DOCSP-4806) Create a new Sampling page

source/faq.txt, source/includes/extracts-query-bar.yaml, source/includes/toc-manage-data.yaml, source/manage-data.txt, source/sampling.txt, source/schema.txt
* Creating Sampling page, updated refs
* Sampling page
* Wrap at 72
* Updates from copy review
* Move Sampling page to bottom of ToC
This PR introduces: https://github.com/mongodb/docs-compass/pull/239
=> (DOCSP-4806) Create a new Sampling page (#239)

source/includes/steps-export-filter.yaml
Fixes a reference to an old sampling page - it was pushed to beta right before the sampling page update.
=> Updated a reference to an old sampling page

source/aggregation-pipeline-builder.txt, source/connect/favorite-connections.txt, source/query/favorites.txt, source/upgrade.txt
@mmarcon, these address the updates for [DOCSP-9295](https://jira.mongodb.org/browse/DOCSP-9295). I added the file locations for all saveable items.
Staging:
[Favorite Connections](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-9295/connect/favorite-connections.html#save-a-favorite-connection)
[Agg Pipelines](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-9295/aggregation-pipeline-builder.html#save-a-pipeline)
[Favorite Queries](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-9295/query/favorites.html)
=> (DOCSP-9295): Adding file locations for saved favorites

source/index.txt
Moved the source-available section higher on the page and simplified the language a bit.
JIRA: [DOCSP-9824](https://jira.mongodb.org/browse/DOCSP-9824)
Staged: [Landing Page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-9824/index.html)
=> (DOCSP-9824): Move source-available info higher on landing page

source/documents/insert.txt, source/includes/fact-automatic-objectid.rst
Added note stating automatic creation of an object ID when one is not provided during document insertion.
Jira: https://jira.mongodb.org/browse/DOCSP-10869
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-10869/index.html
=> (DOCSP-10869) Note on Automatic Creation of Object ID

source/documents/insert.txt, source/includes/fact-automatic-objectid.rst
* (DOCSP-10869) Note on Automatic Creation of Object ID. Master copy was approved #267 
Co-authored-by: Jocelyn Mendez <jocelynmendez@Jocelyns-MacBook-Pro.local>
=> (DOCSP-10869) Note on Automatic Creation of Object ID (#267)

source/release-notes.txt
Add note about an added embedded MongoDB Shell and linked back to embedded MongoDB Shell page for more info.
jira: https://jira.mongodb.org/browse/DOCSP-10856
staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-10856/release-notes.html
=> (DOCSP-1085)- Release notes for 1.22 about added embedded MongoDB Shell

source/install.txt
Added step number 7 to note how to allow macOS to trust Compass in order to fix/prevent security error.
Jira: https://jira.mongodb.org/browse/DOCSP-10756#add-comment
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-10756/index.html
=> DOCSP-10756) Added step noting directions for Compass to trust macOS

source/install.txt, source/upgrade.txt
Added note that macOS Catalina, and later versions, may require permission to be granted to allow Compass to run. 
jira: https://jira.mongodb.org/browse/DOCSP-11049
staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/jocelynmendez/DOCSP-11049/index.html
=> (DOCSP-11049) Added note on macOS permission for Compass to run

source/query-plan.txt, source/upgrade.txt
Added note that Explain tab is not available for aggregation and referred users to .explain() method.
Jira: https://jira.mongodb.org/browse/DOCSP-11062
staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker/DOCSP-11062/query-plan.html
=> (DOCSP-11062) Added limitation for aggregation

source/includes/steps-create-index.yaml, source/indexes.txt
Creating wildcard indexes is not very intuitive in Compass. This attempts to clarify the process a bit by adding more detail and examples.
Staged: [Manage Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-11197/indexes.html#create-an-index)
=> (DOCSP-11197): Wildcard index clarifications

source/documents/modify.txt
Consolidated the Read-only limitation and this new limitation to a new `Limitations` section at the top of the page.
See staging: [Modify Documents](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-11872/documents/modify.html)
=> (DOCSP-11872): Add limitation for updating sharded collection

source/install.txt
These changes were made in light of [DOCSP-12925](https://jira.mongodb.org/browse/DOCSP-12925). Please see my comment on that ticket and let me know if there is anything specific we need to address for Ubuntu 20.04.
The changes here update the Linux install experience to be terminal-only (using `wget`), as opposed to navigating to Download Center
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-12925/install
=> (DOCSP-12925): Refactor Linux Install

source/includes/steps-starting-compass-individual-fields.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-13518)
[Staged: Fill in Individual Fields > step 2 > Authentication > X.509 tab](https://docs-mongodbcom-staging.corp.mongodb.com/compass/zach.carr/DOCSP-13518/connect.html)
Providing a Username is now essentially optional - it gets pulled from the X.509 cert. 
However, in some cases where a user has generated their own X.509 cert, they may still need to supply the username. This sounds like an edge case and I'm not sure how much we should highlight that. I added a note that aims to reassure users who aren't entering the Username and give users who run into errors a clue as to what went wrong.
=> (DOCSP-13518) X509 username field is optional

source/documents/modify.txt, source/includes/fact-modify-findOneAndReplace.rst, source/includes/fact-modify-findOneAndUpdate.rst, source/includes/fact-modify-prevent-overwrites.rst
[(DOCSP-12499)](https://jira.mongodb.org/browse/DOCSP-12499)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5ff3ed36ceb0c9c2e50e9838)
[Staging: Modify Documents](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-12499/documents/modify)
- Made the changes for the ticket. Indicated which API is used. Described what happens when users modify fields.
- Added missing alt text to screenshots. Without alt text, the current build generated warnings and screenshots didn't display. 
- Fixed heading levels. Without this fix, some content was not displaying for the List view and Table view (regardless of the changes for this ticket -- so this was a bug that I fixed). 
Please review!
=> (DOCSP-12499) documents are now updated not replaced, when modified

source/documents/modify.txt, source/includes/fact-modify-findOneAndReplace.rst, source/includes/fact-modify-findOneAndUpdate.rst, source/includes/fact-modify-prevent-overwrites.rst
Backporting DOCSP-12499 to Compass beta. 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5ff76062c5bd3658da3f0932) (warnings are there for **_another_** [open ticket DOCSP-11896](https://jira.mongodb.org/browse/DOCSP-11896) ) -- they do not affect the display or changes made for my ticket or for this backport.
* (DOCSP-12499) documents are now updated not replaced, when modified
* Included tech review and implemented includes
=> (DOCSP-12499) documents are now updated not replaced, when modified (#319)

source/includes/steps-starting-compass-individual-fields.yaml
@mongomoe, I removed references about completing the username field for x.509 authentication from the following page (Select the Fill in Individual Fields tab, see step 2, Authentication, and then the X.509 tab.):
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-14430/connect/#enter-your-connection-information)
[JIRA](https://jira.mongodb.org/browse/DOCSP-14430)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=602c1ed7ab23346c20cac698)
=> (DOCSP-14430): Removed references about completing the username field for x.509 authentication.

source/documents/modify.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603455b2ab23346c203b34a1) has no issues.
[Jira](https://jira.mongodb.org/browse/DOCSP-14727) asked to remove the limitation. 
[Staging shows only one bullet in limitations](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-14727/documents/modify/), instead of [two limitations in the current topic](https://docs.mongodb.com/compass/current/documents/modify).
Please let me know if I can skip tech review for this one!
=> (DOCSP-14727) Remove limitation that you cannot use the UI to make updates in sharded collections

config/redirects
Updating redirects to use the canonical URL and thus remove some redirect steps. This is part of the high-priority SEO work. Also removed the symlink that has no meaning in Snooty.
Produced redirect file:
```
Redirect 301 /compass/beta-features https://docs.mongodb.com/compass/
Redirect 301 /compass/1.3-features https://docs.mongodb.com/compass/
Redirect 301 /compass/index.html https://docs.mongodb.com/compass/current/
Redirect 301 /compass/ https://docs.mongodb.com/compass/current/
Redirect 301 /compass/manual/aggregation-pipeline-builder https://docs.mongodb.com/compass/current/aggregation-pipeline-builder/
Redirect 301 /compass/master/query-bar https://docs.mongodb.com/compass/master/query/filter/
Redirect 301 /compass/beta/query-bar https://docs.mongodb.com/compass/beta/query/filter/ …
```
=> DOP-1883: use canonical links for redirects

source/install.txt
Backporting this [commit](https://github.com/mongodb/docs-compass/commit/a7ccc2008e96ccd5f8c4ca1cde4c794435ddfcb1) to Compass Beta. 
#332 
[Jira](https://jira.mongodb.org/browse/DOCSP-14404)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6047a55875e817aef7de3b32) has no issues.
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-14404-beta/install/), see the line about installing as an administrator, in the bulleted list.
Screenshot below:
=> (DOCSP-14404) Backporting to Compass Beta of PR #332

source/aggregation-pipeline-builder.txt
Fixing an indentation issue and restoring an intro sentence.  All are fixes for missed issues in #345. No need to review as no changes introduced, just formatting issues fixed. 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=608b396409293ae626ee6a0a) is clean.
=> Fixing formatting issues introduced and missed by prev PR

source/query/filter.txt, source/query/queries.txt
Oleg, I added a UUID example and shortened the tab labels on the following page. I also fixed a small issue that was causing build errors.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-13886/query/filter/#examples)
[JIRA](https://jira.mongodb.org/browse/DOCSP-13886)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=609d6766f1f693745040d718)
=> (DOCSP-13886): Added a UUID example.

source/release-notes.txt
Compass no longer automatically sets directConnection=true and now user must declare it explicitly.
JIRA: https://jira.mongodb.org/browse/DOCSP-20458?filter=-1
STAGING:  https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-20458/release-notes/
=> DOCSP-20458 directConnection=true must now be declared

source/includes/steps-starting-compass-individual-fields.yaml, source/release-notes.txt
* DOCSP-20400 replica sets can connect using Socks5
* DOCSP-20400 replica sets can connect using Socks5
* DOCSP-20400 replica sets connect using ssh tunnel
* DOCSP-20400 replica set and shared clusters can connect using SSH tunnel
* DOCSP-20400 replica set and shared clusters can connect using SSH tunnel
* DOCSP-20400 fixed typo
Co-authored-by: Jocelyn Mendez <jocelyn.mendez@Jocelyns-MacBook-Pro.local>
=> DOCSP-20400 replica sets can connect using Socks5 (#372)

source/faq.txt, source/release-notes.txt, source/troubleshooting.txt, source/troubleshooting/connection-errors.txt, source/troubleshooting/logs.txt
This was a feature introduced a while ago that we missed documenting. As noted in [DOCSP-21469](https://jira.mongodb.org/browse/DOCSP-21469), in addition to creating a main page for logging, we also want to update the Troubleshooting, FAQ, and Release Notes for this feature.
- [Retrieve Compass Logs](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-18928/troubleshooting/logs/)
- [New FAQ Item](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-18928/faq/#where-can-i-find-compass-logs-)
- [Connection Troubleshooting](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-18928/troubleshooting/connection-errors/#check-the-compass-logs)
- [1.29.4 Release …
=> (DOCSP-18928): Compass logs

source/includes/fact-release-notes-1.11.rst, source/indexes.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-22723-fix-brokewn-link-v6.0/indexes/#indexes-tab)  - just above this point
[staging - build error](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-22723-fix-brokewn-link-v6.0/release-notes/#compass-1.11)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22723)
Also fixes an existing build error
=> DOCSP-22723 fix broken link

snooty.toml, source/release-notes.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-23128/release-notes/
=> (DOCSP-23128): Compass 1.32.1 and 1.32.2 release notes

snooty.toml, source/release-notes.txt
Copy and paste from the 1.35 [whats changed](https://github.com/mongodb-js/compass/releases) section. Removed a few items that are not relevant for the release
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27268/release-notes/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63beeecddc742b91f29bc0a3
https://jira.mongodb.org/browse/DOCSP-27268
=> DOCSP-27268 Compass 1.35 release notes

source/command-line-options.txt, source/connect/connect-from-the-command-line.txt
Adding command line arguments username and password to the Compass CLI page + adding an example
https://docs-mongodborg-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26528/connect/connect-from-the-command-line/#command-line-connection-specification
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63af1c0edc742b91f27e8c66
https://jira.mongodb.org/browse/DOCSP-26528
=> DOCSP-26528 Adding username and password parameters to CLI page

source/aggregation-pipeline-builder.txt, source/command-line-options.txt
Adding callout that Additional stages `$search` and `$serchMeta` are available when a user connects compass to Atlas. 
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27090/aggregation-pipeline-builder/
https://jira.mongodb.org/browse/DOCSP-27090
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63a475c8dc742b91f284ed12
=> DOCSP-27090 Add Atlas only stage note

source/embedded-shell.txt
Add information about disabling/enabling the embedded shell on the settings interface. Opted to focus on disabling since there are other relevant circumstances to note alongside it (i.e. limitations of set read-only mode)
https://jira.mongodb.org/browse/DOCSP-26519
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26519-enable-shell-ui-settings/embedded-shell/#disable-the-embedded-mongodb-shell
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63ecf46fdcefe97797aa76b3
=> DOCSP-26519 Enable Shell UI Settings

source/collections/time-series-collection.txt, source/upgrade.txt
Add `bucketMaxSpanSeconds` and `bucketRoundingSeconds` fields to the Compass Create a Time Series Collection page.
**STANDING QUESTION(S)**
- For the table of fields, would it help to add a `Type` column that specifies what type of value is expected for each field, or do we expect the user to go the corresponding Server page for more details on that? 
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27956-buckmaxspanseconds-bucketroundingseconds/collections/time-series-collection/#specify-a-timefield.
https://jira.mongodb.org/browse/DOCSP-27966
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63f7c92205dd3cc81464e278
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+ …
=> DOCSP-27956 Add bucketMaxSpanSeconds and bucketRoundingSeconds

source/config-file/config-file-options.txt
Adds information about sample configuration file that can be found with the `--show-example-config` flag.
Also notes command that can be run to use the sample config file (this information is found when you run --help).
**Note**: This content will likely be moved around in terms of placement during IA-change phase of this project.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26725-sample-config-file/config-file/config-file-options/#example
https://jira.mongodb.org/browse/DOCSP-26725
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64065d37054271fb0ab49c3c
=> DOCSP-26725 Sample Configuration File option

source/config-file.txt, source/config-file/config-file-options.txt, source/config-file/protect-connection-strings.txt, source/connect/connect-from-the-command-line/command-line-options.txt, source/includes/fact-protect-connection-strings.rst
- Moved existing description of `protectConnectionStrings` options to an include. 
- Created task page for enabling `protectConnectionStrings` in the CLI and config file. 
**Note:** The instructions for enabling this setting on the Settings UI will be documented in a soon-to-follow ticket.
- [Added to list of Tasks on Config File Options page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26281-protectconnectionstrings-option/config-file/#tasks)
- [Hide Credentials, Task Page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26281-protectconnectionstrings-option/config-file/protect-connection-strings/)
- [Config File Options](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26281-protectconne …
=> DOCSP-26281 Add protectConnectionStrings option

source/settings/protect-connection-strings.txt
Add steps for setting `protectConnectionStrings` in the Compass settings UI to existing task page. 
- [Entry in Settings table](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26539-protectconnectionstrings-ui/settings/settings-reference/#settings)
- [Settings UI Procedures](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26539-protectconnectionstrings-ui/settings/protect-connection-strings/#compass-short-settings-panel)
https://jira.mongodb.org/browse/DOCSP-26539
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6421d3f2b070a41637c4b912
=> DOCSP-26539 protectConnectionStrings in settings UI

source/release-notes.txt
Adds release notes for 1.36.0 and 1.36.1.
* [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27560-compass-rn-1.36.0/release-notes/)
* [DOCSP-27560](https://jira.mongodb.org/browse/DOCSP-27560)
* [DOCSP-28596](https://jira.mongodb.org/browse/DOCSP-28596)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=641358e7b070a41637f078f2)
=> DOCSP-27560/DOCSP-27560 Compass RN 1.36.0 and 1.36.1

source/settings.txt, source/settings/read-only.txt, source/settings/settings-reference.txt
- Add task page for setting `readOnly` option
- Add to task list in Settings concept + reference pages
- [New task page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26520-readonly-setting/settings/read-only/)
- [Task list on concept page](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26520-readonly-setting/settings/#tasks)
- [Reference page table entry](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26520-readonly-setting/settings/settings-reference/#:~:text=Definition-,Set%20Read%2DOnly%20Mode,-General)
https://jira.mongodb.org/browse/DOCSP-26520
UPDATED: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642af2a666f244bf57b7f10a
[What's expected of an …
=> DOCSP-26520 readOnly Settings

source/embedded-shell.txt, source/faq.txt, source/settings/command-line-options.txt, source/upgrade.txt
Removes information about now-removed Crash Report collection option. 
Also edited some incorrect settings procedures I happened to catch along the way.
- [FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26694-remove-crash-report-collection-option/faq/#how-do-i-view-and-modify-my-privacy-settings-)
- [Command Line Settings ](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26694-remove-crash-report-collection-option/settings/command-line-options/#general-settings)
https://jira.mongodb.org/browse/DOCSP-26694
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642dd6a2b49106a498ae7e66
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+ …
=> DOCSP-26694 Remove Information about Crash Report Collection

source/settings/settings-reference.txt
- Adds `installURLHandlers` to settings reference page
- No task page associated with this because the setting is enabled by default and the desired use case is that a user would want to keep it enabled. 
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-26724-compass-protocol-handler/settings/settings-reference/#:~:text=Chrome%20DevTools.-,Install%20Compass%20as%20URL%20Protocol%20Handler,-General
https://jira.mongodb.org/browse/DOCSP-26724
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642f0f40b49106a498f0d4a7
=> DOCSP-26724 Register Compass as a Protocol Handler

source/settings/config-file/config-file-options.txt
Update reference table of configuration options.
Note: The build error/missing ref will be resolved once #480 is merged.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29045-reference-page-updates/settings/config-file/config-file-options/#settings
https://jira.mongodb.org/browse/DOCSP-29045
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64342f64b49106a498d7cdbe
=> DOCSP-29045 reference page updates

source/release-notes.txt
Adds release notes for Compass 1.36.2.
[Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-28851-1.36.2-release-notes/release-notes/#compass-1.36.2)
[DOCSP-28851](https://jira.mongodb.org/browse/DOCSP-28851)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64514c687efd2382b3428009)
=> DOCSP-28851 Adds release notes for Compass 1.36.2

source/release-notes.txt
Adds release notes for 1.36.4.
* [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29494-release-notes-1.36.4/release-notes/#compass-1.36.4)
[DOCSP-29494](https://jira.mongodb.org/browse/DOCSP-29494)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64528e597efd2382b387d74b)
=> DOCSP-29494 Add Compass 1.36.4 Release Notes

source/install.txt
Quick win: removing Rosetta install mentions for the M1 Mac, which is no longer required.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-29851/install/
https://jira.mongodb.org/browse/DOCSP-29851
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6463988cdf0f8173e92b33f2
=> DOCSP-29851 Remove Rosetta Install Mentions

snooty.toml
Updating version in snoty.toml so that the wget commands on the linux installation tab point to the most recent release.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-30085/install/
https://jira.mongodb.org/browse/DOCSP-30085
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=646cbb29df0f8173e9f08c2a
=> DOCSP-30085 Bumping current-version in snooty.toml

config/redirects
Create re-direct from [deleted dark mode page](https://www.mongodb.com/docs/compass/current/dark-mode/) to [Settings UI page](https://www.mongodb.com/docs/compass/current/settings/settings-reference/).
NOT AVAILABLE FOR REDIRECT
https://jira.mongodb.org/browse/DOCSP-30120
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=646e1bfbdf0f8173e93f28db
=> DOCSP-30120 Create Re-Direct for Dark Mode Page

config/redirects
Added a redirect for the now-deleted Config File Options page -> redirected to the new config file reference page.
N/A for redirect links
https://jira.mongodb.org/browse/DOCSP-30779
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648c85ae259a8493e5f9eaac
=> DOCSP-30779 Config File Reference Redirect

source/install.txt
Adds note to installation page that Compass doesn't support virtual desktop evironments.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-21553-virtual-desktops-not-supported/install/#download-and-install-compass
https://jira.mongodb.org/browse/DOCSP-21553
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64af1278423952aeb9bbd954
=> DOCSP-21553 Virtual Desktops Not Supported

source/release-notes.txt
Release Notes for Compass 1.38.1.
* [RN](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-31030-1.38.1-release-notes/release-notes/#compass-1.38.1)
[DOCSP-31030](https://jira.mongodb.org/browse/DOCSP-31030)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649ef22a423952aeb9fbce80)
=> DOCSP-31030 Release Notes for 1.38.1

config/redirects
Fixes typo in redirects.
No staging since these are redirects. Here's the result of running `mut-redirects config/redirects`
`Redirect 301 /docs/compass/current/dark-mode/ https://www.mongodb.com/docs/compass/current/settings/settings-reference/#settings`
`Redirect 301 /docs/compass/current/config-file/config-file-options/ https://www.mongodb.com/docs/compass/current/settings/config-file/`
https://jira.mongodb.org/browse/DOCSP-31564
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64bebd0587b3b360468b7a97
=> DOCSP-31564 Fix Non-working Redirects

source/includes/extracts-query-bar.yaml, source/query/filter.txt
Added two new examples to the Compass query bar page:
- Match on multiple conditions ($and)
- Match with $or.
As part of these updates, I reformatted the query bar examples to not use tabs. This way, the example headings appear in the right-hand toc and act as jump-list so users can quickly find examples. The new examples are noted in the in-line comments.
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32094/query/filter/#examples
https://jira.mongodb.org/browse/DOCSP-32094
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64da4b5b67dbe910108ee119
=> DOCSP-32094 Add more query examples

source/connect.txt, source/connect/favorite-connections.txt, source/includes/fact-legacy-connections.rst
Make/edit note on legacy connections no longer being supported within Compass "Connect" and "Favorite Connections" pages. 
- Added a link to the created include to direct users to the 1.39.0 binary files.
- [Connect to MongoDB (Considerations)](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32147-list-legacy-connections/connect/#considerations)
- [Favorite Connections ](https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32147-list-legacy-connections/connect/favorite-connections/)- put here since legacy connections revolve around those that have been saved.
https://jira.mongodb.org/browse/DOCSP-32147
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64f787f924fcc731b48aaf28
[What's expected of an …
=> DOCSP-32147 Legacy Connections

snooty.toml, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/install.txt, source/query/filter.txt, source/query/sort.txt
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32260/install/
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32260/query/filter/
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-32260/query/sort/
https://jira.mongodb.org/browse/DOCSP-32260
https://jira.mongodb.org/browse/DOCSP-32261
https://jira.mongodb.org/browse/DOCSP-32031
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ff7b1524fcc731b43423ab
=> DOCSP-32260 adds atlas centric cta to pages

snooty.toml, source/includes/steps-create-index.yaml, source/indexes.txt, source/indexes/create-search-index.txt
Document that you can manage Atlas Search indexes in Compass. For details about Atlas Search index syntax, we will point users to the Atlas docs.
- [Manage Indexes](https://preview-mongodbjeffallenmongo.gatsbyjs.io/compass/DOCSP-29554/indexes/)
- [Create an Atlas Search Index](https://preview-mongodbjeffallenmongo.gatsbyjs.io/compass/DOCSP-29554/indexes/create-search-index/#std-label-compass-create-search-index)
https://jira.mongodb.org/browse/DOCSP-29554
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=651301c4492df295cff67a72
=> (DOCSP-29554): Ability to manage Atlas Search Indexes

source/collections.txt, source/connect.txt, source/import-export.txt, source/install.txt, source/query/filter.txt, source/query/queries.txt, source/query/sort.txt, source/release-notes.txt
Add link to Electron v26.2.2 release notes to Compass 1.40.0 RN. 
https://preview-mongodbajhuhmdb.gatsbyjs.io/compass/DOCSP-33413-compass-electron-rn/release-notes/#:~:text=Upgrade%20Electron%20to,version%2026.
https://jira.mongodb.org/browse/DOCSP-33413
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=651c5763492df295cf2a618b
=> DOCSP-33413 Add Electron Release Notes Link to Compass

snooty.toml
Removed the following banner text from Compass GAI pages: 
```
"This feature is on a rolling release schedule. As a result, some users may temporarily have functionality 
that other users do not."
```
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-33662/query-with-natural-language/query-with-natural-language/
https://jira.mongodb.org/browse/DOCSP-33662
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=652d761f673b813c8f0afc9b
=> DOCSP-33662 Remove Incremental Rollout Notice

config/redirects
Updates redirects for the aggregation pipeline builder page to cover all potential branch/URL names.
n/a for redirects
(see comment below for `mut-redirects` output)
https://jira.mongodb.org/browse/DOCSP-33814?filter=-2
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=653286ac3ede3ec111928c3c
=> DOCSP-33814 Aggregation Pipeline Builder Redirect

.vscode/settings.json, snooty.toml, source/in-use-encryption-tutorial.txt
Updates banners in Compass to get rid of 6.0 QE "Public Preview" language
[In-Use Encryption Tutorial](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/compass/DOCSP-33682-fix-QE-banners/in-use-encryption-tutorial/)
Compass v7.0 docs
https://jira.mongodb.org/browse/DOCSP-33682
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=653fca38bd8a7a957943d658
=> Updated banner text, added doc constants

source/includes/fact-natural-language-querying-maxTimems.txt, source/query-with-natural-language/prompt-natural-language-aggregation.txt, source/query-with-natural-language/prompt-natural-language-query.txt, source/release-notes.txt
Adding a consideration for setting ``maxTimeMs`` when using natural language querying.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-32903/query-with-natural-language/prompt-natural-language-query/#about-this-task
https://jira.mongodb.org/browse/DOCSP-32903
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65400f1dbd8a7a957959403a
=> DOCSP-32903 Natural Querying Limits

source/query/filter.txt
adding "new" to match by date example
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-33792/query/filter/#match-by-date
https://jira.mongodb.org/browse/DOCSP-33792
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65491c4abd8a7a957951a2d2
=> DOCSP-33792 match by date error

config/redirects
Corrects redirect links to the current agg pipeline builder link
N/A but `mut-redirect` output show below in comments
https://jira.mongodb.org/browse/DOCSP-34660
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656a06bb7a5cb5fef5e8f83c
=> DOCSP-34660  Infinite Loop Redirects, Missing End Line, Correct URL

source/collections.txt, source/connect.txt, source/index.txt, source/install.txt, source/query/filter.txt, source/query/queries.txt, source/query/sort.txt
Hey @sarah-olson-mongodb!  I'm adding descriptions to the top 250 pages that don't have them, and here are the Compass pages that needed them.  I mostly just copied from the page text, but please check for coherence & conventions and edit as you see fit.
Thanks!
Sarah
https://preview-mongodbsarahemlin.gatsbyjs.io/compass/DOCSP-33172/
https://jira.mongodb.org/browse/DOCSP-33172
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655cf2445b686d6bd98a3c30
=> DOCSP-33172 added meta description for top 250 pages in docs-compass

source/query/filter.txt
Compass automatically adds curly braces to filter input text
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-32117/query/filter/
https://jira.mongodb.org/browse/DOCSP-32117
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659d833bdcc0144a518df554
=> DOCSP-32117 default curly braces in query

source/validation.txt
schema validation no longer auto updates in Compass
https://docs-mongodbcom-staging.corp.mongodb.com/compass/docsworker-xlarge/DOCSP-27810/validation/#validation-rules
https://jira.mongodb.org/browse/DOCSP-27810
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a6f1f2dcc0144a51094dfb
=> DOCSP 27810 updating schema validation behavior 

source/connect/advanced-connection-options/advanced-connection.txt, source/includes/fact-non-utf8-data.rst, source/query/filter.txt
This edit adds mention to the nodejs / Compass URI option `enableUtf8Validation` which allows Compass to show collections that contain invalid UTF8 data. This additional option needs mention on https://www.mongodb.com/docs/drivers/node/current/fundamentals/connection/connection-options/, it works as [both a client parameter](https://www.mongodb.com/docs/drivers/node/current/fundamentals/bson/utf8-validation/#specify-the-utf-8-validation-setting) and a URI connection string option. 
Parsing logic: https://github.com/mongodb/js-bson/blob/main/src/parser/deserializer.ts#L678. 
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-23996/query/filter/#query-collections-with-invalid-utf8-data
https://jira.mongodb.org/browse/DOCSP-23996 …
=> DOCSP-23996 Add enableUtf8Validation Connectionstring Option

source/query/filter.txt
Fixes syntax example in query page to reflect use of `$and` oeprator.
https://preview-mongodbajhuhmdb.gatsbyjs.io/compass/DOCSP-35718-query-data-syntax/query/filter/#match-by-multiple-conditions---and-
https://jira.mongodb.org/browse/DOCSP-35718
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ae81ef30987d50507ec5bf
=> DOCSP-35718 Query Data '$and' Syntax

source/release-notes.txt
Somehow when merging #591  1.41.0 release notes got put higher on the page than the latest release 1.42.0 release notes. This is a quick fix to remedy the release notes ordering.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-35111-b/
https://jira.mongodb.org/browse/DOCSP-35111
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c238f86b2f17c95a5172ff
=> DOCSP-35111 Reorganize release notes order

source/includes/fact-protect-connection-strings.rst, source/settings/config-file.txt
documenting new global config property `protectConnectionStringsForNewConnections`
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-29957/settings/config-file/#settings
https://jira.mongodb.org/browse/DOCSP-29957
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c10d026b2f17c95afaf410
=> DOCSP-29957 protectConnectionStringsForNewConnections parameter

source/settings/settings-reference.txt
Document new buttons in the UI to access Compass' settings.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-29775/settings/settings-reference/#settings-panel-location
https://jira.mongodb.org/browse/DOCSP-29775
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ccfdcacbcd269fa534ef15
=> DOCSP-29775 document add button to open settings to sidebar

source/collections/capped-collection.txt, source/collections/clustered-collection.txt, source/collections/collation-collection.txt, source/collections/encrypted-collection.txt, source/collections/time-series-collection.txt, source/in-use-encryption-tutorial.txt, source/includes/steps-create-collection.yaml
Documents that Time Series checkbox and all the options that it supports are now right underneath the name of the collection. Also replaces GUI label **Advanced Collection Options** to **Additional Preferences** across pages.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-28027/collections/time-series-collection/
https://jira.mongodb.org/browse/DOCSP-28027
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cfcfb67111165982695a33
=> DOCSP-28027 document Time series option UI changes

source/query-with-natural-language/ai-and-data-usage-information.txt, source/query-with-natural-language/query-with-natural-language.txt
Adding a `AI and Data Usage Information` page to the Natural Language Querying Drawer.
LGTM'd over slack.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-37108/query-with-natural-language/ai-and-data-usage-information/
https://jira.mongodb.org/browse/DOCSP-37108
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d7aae47111165982588c3a
=> DOCSP-37108 Add Compass AI and Data Usage Info Page

source/documents/modify-multiple.txt
Adding a recently discovered caveat to using the document preview modal in the Compass multiple modify workflow.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-37238/documents/modify-multiple/
https://jira.mongodb.org/browse/DOCSP-37238
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e0d41d11db7b0427468d7d
=> DOCSP-37238 Add note about transactions to bulk update

source/includes/steps-create-index.yaml
No changes to **Partial Filter Expression** as documentation doesn't specify UI field format for any of the options in the list. Moved **Custom Collation** row above **Wildcard Projection**.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-24886/indexes/#optional-specify-index-options
https://jira.mongodb.org/browse/DOCSP-24886
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ef50096fc5f0485077d671
=> DOCSP-24886 update create index options

source/query/filter.txt
The documented MongoDB aggregation in the example doesn't work. I tested and got an error:
```
Atlas atlas-l1dbhc-shard-0 [primary] my_test> db.users.aggregate(
...   { $filter : { name : { $eq : "Andrea Le" } } }
... );
MongoServerError[AtlasError]: $filter is not allowed or the syntax is incorrect
```
Tested example suggested in the ticket and modified example accordingly:
```
Atlas atlas-l1dbhc-shard-0 [primary] my_test> db.users.aggregate({$match: {"name": "Andrea Le"}})
[
{
_id: ObjectId('65ef30aa6f0e4dfbf15d143d'),
name: 'Andrea Le',
email: 'andrea_le@fake-mail.com',
version: 5,
scores: [ 85, 95, 75 ],
dateCreated: ISODate('2003-03-26T00:00:00.000Z')
}
]
```
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-27227/query/filter/#how-does-the-compass-query-compare-to-mong …
=> DOCSP-27227 Clarify MongoDB Aggregation in Compass Filter Doc

source/release-notes.txt
Compass 1.42.3 Release Notes
https://preview-mongodbajhuhmdb.gatsbyjs.io/compass/DOCSP-37819-compass-1.42.3-rn/release-notes/#compass-1.42.3
https://jira.mongodb.org/browse/DOCSP-37819
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65fda8de6fc5f04850ff6472
^ new build error doesn't seem to be related to this PR. seems to involve an include getting mistakenly parsed as a text page.
=> DOCSP-37819 Compass 1.42.3 Release Notes

source/query-plan.txt
Documents that when requesting explain plan for aggregation pipelines, out stages like $merge and $out are now ignored / removed from the pipeline.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/compass/DOCSP-33037/query-plan/
https://jira.mongodb.org/browse/DOCSP-33037
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6605abc86fc5f04850db683c
=> DOCSP-33037 doc that some out stages are now filtered out

snooty.toml, source/release-notes.txt
Adds release notes for 1.42.5 and a note that 1.42.4 was not released.
https://preview-mongodbmdbashley.gatsbyjs.io/compass/DOCSP-38377-1.42.5-release-notes/release-notes/
https://jira.mongodb.org/browse/DOCSP-38377
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661826013a5920a291491b7d
=> Release notes for 1.42.5

source/settings/config-file.txt, source/settings/read-only.txt
Typo: It's enableDevTools, not enableDevtools.
https://preview-mongodbsaraholsonmongodb.gatsbyjs.io/compass/DOCSP-38842/settings/config-file/#settings
https://preview-mongodbsaraholsonmongodb.gatsbyjs.io/compass/DOCSP-38842/settings/read-only/
https://jira.mongodb.org/browse/DOCSP-38842
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662303b7b67dbf804a8e3b83
=> DOCSP-38842: Fixes typo in two places

source/query-with-natural-language/ai-and-data-usage-information.txt, source/settings/settings-reference.txt
- Document the new `Artificial Intelligence` setting `Enable sending sample field values with query and aggregation generation requests` introduced in `1.43.1`. 
- Note after discussion with Rhys, the setting will be updated to `Enable sending sample field values`.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-40181/settings/settings-reference/#settings
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-40181/query-with-natural-language/ai-and-data-usage-information/#how-your-data-is-used
https://jira.mongodb.org/browse/DOCSP-40181
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6668a479ebce19f3140003c1
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Docum …
=> DOCSP-40181 Compass GenAI Sample Documents

source/release-notes.txt
Release notes per JIRA request. 2 items don't have JIRA issues associated with them, but left them in with description. Other release notes do a similar thing with fixes that don't have JIRAs.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/compass/DOCSP-40841-release-notes-1.43.2/release-notes/#compass-1.43.2
https://jira.mongodb.org/browse/DOCSP-40841
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667b4090ebce19f314157e33
=> DOCSP-40841-release-notes-1.43.2

source/connect/advanced-connection-options/authentication-connection.txt
Fixes typo on compass authentication connection page.
https://preview-mongodbjmdmongo.gatsbyjs.io/compass/DOCSP-40984/connect/advanced-connection-options/authentication-connection/#kerberos
https://jira.mongodb.org/browse/DOCSP-40984
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667ed6d6fe162e5006082ba7
=> DOCSP-40984 auth connection page typo

conf.py, source/keyboard-shortcuts.txt, source/settings/settings-reference.txt
- Add quit setting to the settings page.
- Updated all keyboard short cuts to use `:kbd:` role.
- Updated the close window hotkey to be cmd + shift + w to reflect recent app change.
- Add ref to the keyboard shortcuts page.
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-40542/settings/settings-reference/#settings
https://preview-mongodbianfmongodb.gatsbyjs.io/compass/DOCSP-40542/keyboard-shortcuts/
https://jira.mongodb.org/browse/DOCSP-40542
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6684128efe162e50061300a9
=> DOCSP-40542 Compass Quit Functionality Update

source/indexes/create-vector-search-index.txt
Compass Atlas Vector Search Index updates. 
After discussion with engineering, the compass docs needed the update on the value for the ``numDimensions`` field but the example feedback on the jira ticket does not apply to the compass example.
https://preview-mongodbjocelynmendez1.gatsbyjs.io/compass/DOCSP-41463/indexes/create-vector-search-index/#provide-the-atlas-vector-search-index-configurations
https://jira.mongodb.org/browse/DOCSP-41463
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66993b1a26eba79552154583
=> DOCSP-41463 Compass Atlas Vector Search Index updates

source/import-export.txt
adding a note to prevent users from using Compass as a backup method (amended from the original ticket description based on [this slack thread](https://mongodb.slack.com/archives/C0U7K0MC3/p1721766581019579))
https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-41648/import-export/
https://jira.mongodb.org/browse/DOCSP-41648
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a1255f26eba79552cae2da
=> DOCSP-41648 backup note

source/collections.txt, source/connect.txt, source/connect/advanced-connection-options.txt, source/connect/favorite-connections.txt, source/connect/favorite-connections/import-export.txt, source/create-agg-pipeline.txt, source/documents.txt, source/index.txt, source/indexes.txt, source/install.txt, source/install/verify-signatures.txt, source/manage-data.txt, source/performance.txt, source/query-with-natural-language/query-with-natural-language.txt, source/query/filter.txt, source/query/queries.txt, source/schema.txt, source/settings.txt, source/troubleshooting.txt
Shorten and edit the Compass ToC labels with the following guidelines: https://wiki.corp.mongodb.com/pages/viewpage.action?spaceKey=DE&title=FAQ%3A+Table+of+Contents+Labels
Official style guidelines for the ToC: Official Style Guidelines for the ToC: https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/
https://deploy-preview-666--docs-compass.netlify.app
(all ToC labels can be seen using the drop down menus)
https://jira.mongodb.org/browse/DOCSP-43303
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66d9f8fcf062608452c7a83c
=> DOCSP-43303-Compass-ToC-refactor

source/indexes.txt
Remove reference to shared tier clusters in indexes limitations.
https://preview-mongodbjvincentmongodb.gatsbyjs.io/compass/DOCSP-40217/indexes/#limitations
https://jira.mongodb.org/browse/DOCSP-40217
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667f271dfe162e50062b3e9a
=> DOCSP-40217 -- Remove reference to shared tier clusters in indexes limitations

source/agg-pipeline-builder/aggregation-pipeline-builder-settings.txt, source/connect/advanced-connection-options/general-connection.txt, source/connect/advanced-connection-options/in-use-encryption.txt, source/connect/advanced-connection-options/tls-ssl-connection.txt, source/includes/extended-json-table.rst, source/includes/steps-create-index.yaml, source/includes/steps-export-filter.yaml, source/includes/steps-export.yaml
Fixed compass nested components.
https://deploy-preview-671--docs-compass.netlify.app/connect/advanced-connection-options/general-connection/
https://deploy-preview-671--docs-compass.netlify.app/connect/advanced-connection-options/in-use-encryption/
https://deploy-preview-671--docs-compass.netlify.app/indexes/
https://deploy-preview-671--docs-compass.netlify.app/agg-pipeline-builder/aggregation-pipeline-builder-settings/
https://deploy-preview-671--docs-compass.netlify.app/agg-pipeline-builder/export-pipeline-results/
https://deploy-preview-671--docs-compass.netlify.app/connect/advanced-connection-options/tls-ssl-connection/
https://deploy-preview-671--docs-compass.netlify.app/import-export/
https://jira.mongodb.org/browse/DOCSP-42973 …
=> DOCSP-42973-compass-nested-components

source/includes/steps-create-index.yaml
fixing build errors
https://deploy-preview-674--docs-compass.netlify.app/indexes/
https://jira.mongodb.org/browse/DOCSP-43970
=> DOCSP-42973-fix-build-errors

source/connect/advanced-connection-options/authentication-connection.txt, source/connect/advanced-connection-options/ssh-connection.txt, source/settings/settings-reference.txt
- Documents Compass proxy settings 
- [Proxy / SSH settings](https://deploy-preview-676--docs-compass.netlify.app/connect/advanced-connection-options/ssh-connection/#procedure:~:text=see%20Socks5.-,Application%2Dlevel%20Proxy,-Connects%20to%20a)
- [Settings UI Proxy Settings](https://deploy-preview-676--docs-compass.netlify.app/settings/settings-reference/#settings:~:text=about%20Compass.-,No%20Proxy,-Proxy%20Configuration)
- [OIDC Option](https://deploy-preview-676--docs-compass.netlify.app/connect/advanced-connection-options/authentication-connection/#std-label-oidc:~:text=Use%20Application%2DLevel%20Proxy%20Settings)
https://jira.mongodb.org/browse/DOCSP-41773
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+ …
=> DOCSP-41773 Compass Proxy Settings

config/redirects
Add redirect to new command line options page. Newly added redirects from `mut-redirects` output:
```
Redirect 301 /docs/compass/master/command-line-options/ https://www.mongodb.com/docs/compass/current/settings/command-line-options/
Redirect 301 /docs/compass/beta/command-line-options/ https://www.mongodb.com/docs/compass/current/settings/command-line-options/
Redirect 301 /docs/compass/current/command-line-options/ https://www.mongodb.com/docs/compass/current/settings/command-line-options/
```
N/A
https://jira.mongodb.org/browse/DOCSP-44185
=> DOCSP-44185-cmd-line-options-redirect

source/embedded-shell.txt
Adding MongoDB shell touchpoint
https://deploy-preview-672--docs-compass.netlify.app/embedded-shell/#open-the-embedded-mongodb-shell
https://jira.mongodb.org/browse/DOCSP-43936
=> DOCSP-43936-mongosh-multiple-connections

snooty.toml, source/release-notes.txt
Compass 1.44.5 release notes ([gh release notes](https://github.com/mongodb-js/compass/releases/tag/v1.44.5))
https://deploy-preview-679--docs-compass.netlify.app/release-notes/#compass-1.44.5
https://jira.mongodb.org/browse/DOCSP-44362
=> DOCSP-44362 Compass 1.44.5 release notes

source/settings/enable-dev-tools.txt
The `About this Task` section specifies four options that cannot be enabled if you want to use Chrome DevTools. One of those options is actually a requirement, while the others remain accurate.
Added a prerequisites section, containing a new line highlighting the enabled option requirement and moved the existing disabled option requirements beneath. I also renamed `Procedure` to `Steps`, as I was already updating from our task template.
[Toggle Chrome DevTools](https://deploy-preview-682--docs-compass.netlify.app/settings/enable-dev-tools/#about-this-task)
https://jira.mongodb.org/browse/DOCSP-44413
=> DOCSP-44413-enabling-Chrome-DevTools-Compass-typo

source/validation.txt
This PR changes the Data Lake limitation under Limitations on [the Validations page](https://www.mongodb.com/docs/compass/current/validation/#limitations) for Compass so that it now instead references [Atlas Data Federation](https://www.mongodb.com/docs/atlas/data-federation/), as Atlas Data Lake is now named Atlas Data Federation. 
https://deploy-preview-689--docs-compass.netlify.app/validation/#limitations
https://jira.mongodb.org/browse/DOCSP-44725
=> DOCSP-44725-data-lake-limitation-to-data-federation

source/release-notes.txt
Release notes 1.44.6.
* [RN](https://deploy-preview-691--docs-compass.netlify.app/release-notes/#compass-1.44.6)
* [DOCSP-44873](https://jira.mongodb.org/browse/DOCSP-44873)
=> DOCSP-44873 1.44.6 Release Notes

source/collections.txt, source/create-agg-pipeline.txt, source/databases.txt, source/documents.txt, source/indexes.txt
Adds ref syntax from Atlas docs to prepare for copybara merge. 
n/a
https://jira.mongodb.org/browse/DOCSP-45447
=> DOCSP-45447-Atlas-UI-Refs

source/settings.txt, source/settings/command-line-options.txt, source/settings/config-file.txt, source/settings/protect-connection-strings.txt, source/settings/settings-reference.txt, source/settings/telemetry.txt
Add a task page for toggling Compass telemetry.
Main content is on this new task page: [Configure Telemetry Options](https://deploy-preview-697--docs-compass.netlify.app/settings/telemetry/)
I also added links to the new page on these pages:
- [Interface Settings](https://deploy-preview-697--docs-compass.netlify.app/settings/settings-reference/#settings)
- [Command Line Options](https://deploy-preview-697--docs-compass.netlify.app/settings/command-line-options/#general-settings)
- [Configuration File Settings](https://deploy-preview-697--docs-compass.netlify.app/settings/config-file/#settings)
https://jira.mongodb.org/browse/DOCSP-19979
=> DOCSP-19979-compass-telemetry-options

source/release-notes.txt
1.44.7 release notes
https://deploy-preview-698--docs-compass.netlify.app/release-notes/
https://jira.mongodb.org/browse/DOCSP-45457
=> DOCSP-45457-1.44.7-release-notes

source/settings/command-line-options.txt, source/settings/config-file.txt
Adds missing AI settings to Compass configuration and command-line reference.
* [enableGenAIDocumentPassing Setting](https://deploy-preview-694--docs-compass.netlify.app/settings/config-file/#settings)
* [--enableGenAIFeatures CLI Option](https://deploy-preview-694--docs-compass.netlify.app/settings/command-line-options/#std-option-compass.--enableGenAIFeatures)
* [--enableGenAIDocumentPassing CLI Option](https://deploy-preview-694--docs-compass.netlify.app/settings/command-line-options/#std-option-compass.--enableGenAIDocumentPassing)
[DOCSP-44882](https://jira.mongodb.org/browse/DOCSP-44882)
=> DOCSP-44882 Compass AI Settings

source/troubleshooting/connection-errors.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-38083)
=> (DOCSP-38083) Deprecate blacklist and whitelist terminology.

source/connect/advanced-connection-options/authentication-connection.txt
Updates OIDC connection settings to include the new checkbox `Send a nonce in the Auth Code Request`
Note - the description here is based on the UI [description](https://github.com/mongodb-js/compass/pull/6542/files#diff-337de6f5aba02a6de066c13ea23bfdfed45cf6c661c7200293564278eab343ccR184) in the eng [PR](https://github.com/mongodb-js/compass/pull/6542).
https://deploy-preview-700--docs-compass.netlify.app/connect/advanced-connection-options/authentication-connection/#oidc
https://jira.mongodb.org/browse/DOCSP-45739
=> DOCSP-45739 Adds nonce in Auth Req to OIDC connection settings

source/troubleshooting/connection-errors.txt
Compass docs have a build error:
WARNING(troubleshooting/connection-errors.txt:72ish): Title underline too short.
Relates to a heading around line 125 with a short line.
https://deploy-preview-710--docs-compass.netlify.app/troubleshooting/connection-errors/#atlas-ip-access-list-does-not-include-your-address
[DOCSP-46530](https://jira.mongodb.org/browse/DOCSP-46530)
=> (DOCSP-46530)-Fix-short-title-underline-error

source/release-notes.txt
Compass 1.45.1 Release Notes.
https://deploy-preview-709--docs-compass.netlify.app/release-notes/#compass-1.45.1
https://jira.mongodb.org/browse/DOCSP-46445
=> DOCSP-46445-Compass-1.45.1-Release-Notes

source/connect/advanced-connection-options/in-use-encryption.txt
Removes limitation that in-use encryption is Atlas/Enterprise only
https://deploy-preview-713--docs-compass.netlify.app/connect/advanced-connection-options/in-use-encryption/
https://jira.mongodb.org/browse/DOCSP-46836
=> DOCSP-46836-remove-in-use-encryption-atlas-limitation

source/settings/config-file.txt
add a new proxy setting to the [Compass config file docs. ](https://www.mongodb.com/docs/compass/current/settings/config-file/)
https://deploy-preview-716--docs-compass.netlify.app/settings/config-file/
https://jira.mongodb.org/browse/DOCSP-45732
=> DOCSP-45732-add-proxy-setting-compass-config

source/query/atlas-search.txt
Add caveat to [Atlas Search Query page](https://www.mongodb.com/docs/compass/current/query/atlas-search/) that search stages must be the first stage in your agg pipeline except when you want to combine both vector and full-text search in the same agg pipeline, in which case you would use hybrid search. 
https://deploy-preview-718--docs-compass.netlify.app/query/atlas-search/#construct-your-query
https://jira.mongodb.org/browse/DOCSP-46151
=> DOCSP-46151-mention-hybrid-search-compass

source/release-notes.txt
1.45.2 compass release notes. 
https://deploy-preview-714--docs-compass.netlify.app/release-notes/
https://jira.mongodb.org/browse/DOCSP-46827
=> DOCSP-46827-compass-release

source/release-notes.txt
Adds release notes for 1.45.3
https://deploy-preview-722--docs-compass.netlify.app/release-notes/
https://jira.mongodb.org/browse/DOCSP-47292
=> DOCSP-47292 Adds 1.45.3 Release Notes

snooty.toml, source/release-notes.txt
Release notes for 1.45.4.
[RN](https://deploy-preview-725--docs-compass.netlify.app/release-notes/#compass-1.45.4)
[DOCSP-47969](https://jira.mongodb.org/browse/DOCSP-47969)
=> DOCSP-47969 Compass 1.45.4 RN

source/query-plan.txt
Add note to [View Query Performance page](https://www.mongodb.com/docs/compass/current/query-plan/#view-query-performance) that you can't view VS queries as a visual tree. 
https://deploy-preview-733--docs-compass.netlify.app/query-plan/#view-query-performance
https://jira.mongodb.org/browse/DOCSP-48477
=> DOCSP-48477-vector-search-visual-tree-unavailable

source/troubleshooting/connection-errors.txt
Fix 404 link from outdated ref to `/security-accesslist/` to `/security/ip-access-list/`
https://deploy-preview-735--docs-compass.netlify.app/troubleshooting/connection-errors/
https://jira.mongodb.org/browse/DOCSP-48335
https://app.netlify.com/sites/docs-compass/deploys/67e44c216b201b0008884c44
=> DOCSP-48335-fix-404-urls

snooty.toml, source/validation.txt
Adds `/validation` to `toc_landing_pages` in `snooty.toml`.
=> compass-snooty-drawer

source/connect/advanced-connection-options/general-connection.txt
removing nested components
https://deploy-preview-744--docs-compass.netlify.app/connect/advanced-connection-options/general-connection/
https://jira.mongodb.org/browse/DOCSP-49010
=> DOCSP-49010-new-nested-components

source/includes/large-number-note.rst, source/query/filter.txt
Add information on how to query for large numbers in compass
https://deploy-preview-742--docs-compass.netlify.app/query/filter/
https://jira.mongodb.org/browse/DOCSP-45398
https://app.netlify.com/sites/docs-compass/deploys/67f6e76bf4da2d0008cd45e3
=> DOCSP-45398-detail-large-number-queries

source/indexes/create-vector-search-index.txt
Fix incorrect description of VS type in [Compass docs](https://www.mongodb.com/docs/compass/current/indexes/create-vector-search-index/). 
https://deploy-preview-741--docs-compass.netlify.app/indexes/create-vector-search-index/
https://jira.mongodb.org/browse/DOCSP-48357
=> DOCSP-48357-incorrect-vs-type

source/release-notes.txt
Adds 1.46.1 release notes
https://deploy-preview-746--docs-compass.netlify.app/release-notes/#compass-1.46.1
https://jira.mongodb.org/browse/DOCSP-49449
=> DOCSP-49449 Adds Compass 1.46.1 release notes

source/release-notes.txt
- Added release notes
[Release Notes](https://deploy-preview-747--docs-compass.netlify.app/release-notes/#compass-1.46.2)
https://jira.mongodb.org/browse/DOCSP-49875
=> DOCSP-49875 Compass 1.46.2 release notes
